// This is JoltPhysics.js, a web assembly version of JoltPhysics

var Jolt = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Jolt) {
  Jolt = Jolt || {};


var a;a||(a=typeof Jolt !== 'undefined' ? Jolt : {});var aa,ca;a.ready=new Promise(function(b,c){aa=b;ca=c});var da=Object.assign({},a),ea="./this.program",fa="object"==typeof window,ha="function"==typeof importScripts,ja="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,e="",ka,la,ma,fs,na,oa;
if(ja)e=ha?require("path").dirname(e)+"/":__dirname+"/",oa=()=>{na||(fs=require("fs"),na=require("path"))},ka=function(b,c){oa();b=na.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")},ma=b=>{b=ka(b,!0);b.buffer||(b=new Uint8Array(b));return b},la=(b,c,d)=>{oa();b=na.normalize(b);fs.readFile(b,function(g,h){g?d(g):c(h.buffer)})},1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",
function(b){throw b;}),a.inspect=function(){return"[Emscripten Module object]"};else if(fa||ha)ha?e=self.location.href:"undefined"!=typeof document&&document.currentScript&&(e=document.currentScript.src),_scriptDir&&(e=_scriptDir),0!==e.indexOf("blob:")?e=e.substr(0,e.replace(/[?#].*/,"").lastIndexOf("/")+1):e="",ka=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},ha&&(ma=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),
la=(b,c,d)=>{var g=new XMLHttpRequest;g.open("GET",b,!0);g.responseType="arraybuffer";g.onload=()=>{200==g.status||0==g.status&&g.response?c(g.response):d()};g.onerror=d;g.send(null)};var pa=a.print||console.log.bind(console),k=a.printErr||console.warn.bind(console);Object.assign(a,da);da=null;a.thisProgram&&(ea=a.thisProgram);var qa;a.wasmBinary&&(qa=a.wasmBinary);var noExitRuntime=a.noExitRuntime||!0;"object"!=typeof WebAssembly&&ra("no native wasm support detected");
var sa,ta=!1,ua="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function va(b,c){for(var d=c+NaN,g=c;b[g]&&!(g>=d);)++g;if(16<g-c&&b.buffer&&ua)return ua.decode(b.subarray(c,g));for(d="";c<g;){var h=b[c++];if(h&128){var l=b[c++]&63;if(192==(h&224))d+=String.fromCharCode((h&31)<<6|l);else{var T=b[c++]&63;h=224==(h&240)?(h&15)<<12|l<<6|T:(h&7)<<18|l<<12|T<<6|b[c++]&63;65536>h?d+=String.fromCharCode(h):(h-=65536,d+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else d+=String.fromCharCode(h)}return d}function wa(b){return b?va(xa,b):""}
var ya,xa,m,n,za=[],Aa=[],Ba=[],Ca=!1;function Da(){var b=a.preRun.shift();za.unshift(b)}var p=0,Ea=null,Fa=null;function ra(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";k(b);ta=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ca(b);throw b;}function Ga(){return q.startsWith("data:application/octet-stream;base64,")}var q;q="jolt.wasm.wasm";if(!Ga()){var Ha=q;q=a.locateFile?a.locateFile(Ha,e):e+Ha}
function Ia(){var b=q;try{if(b==q&&qa)return new Uint8Array(qa);if(ma)return ma(b);throw"both async and sync fetching of the wasm failed";}catch(c){ra(c)}}
function Ja(){if(!qa&&(fa||ha)){if("function"==typeof fetch&&!q.startsWith("file://"))return fetch(q,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+q+"'";return b.arrayBuffer()}).catch(function(){return Ia()});if(la)return new Promise(function(b,c){la(q,function(d){b(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return Ia()})}function Ka(b){for(;0<b.length;)b.shift()(a)}
function La(b){this.ud=b-24;this.Jd=function(c){n[this.ud+4>>2]=c};this.Qe=function(c){n[this.ud+8>>2]=c};this.Hd=function(){m[this.ud>>2]=0};this.Pe=function(){ya[this.ud+12>>0]=0};this.Id=function(){ya[this.ud+13>>0]=0};this.Ne=function(c,d){this.Oe();this.Jd(c);this.Qe(d);this.Hd();this.Pe();this.Id()};this.Oe=function(){n[this.ud+16>>2]=0}}var Ma=0,Na={};
function Oa(){if(!Sa){var b={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},c;for(c in Na)void 0===Na[c]?delete b[c]:b[c]=Na[c];var d=[];for(c in b)d.push(c+"="+b[c]);Sa=d}return Sa}var Sa,Ta=[null,[],[]];function Ua(b){return 0===b%4&&(0!==b%100||0===b%400)}
var Va=[31,29,31,30,31,30,31,31,30,31,30,31],Wa=[31,28,31,30,31,30,31,31,30,31,30,31];
function Xa(b){for(var c=0,d=0;d<b.length;++d){var g=b.charCodeAt(d);127>=g?c++:2047>=g?c+=2:55296<=g&&57343>=g?(c+=4,++d):c+=3}c=Array(c+1);g=c.length;d=0;if(0<g){g=d+g-1;for(var h=0;h<b.length;++h){var l=b.charCodeAt(h);if(55296<=l&&57343>=l){var T=b.charCodeAt(++h);l=65536+((l&1023)<<10)|T&1023}if(127>=l){if(d>=g)break;c[d++]=l}else{if(2047>=l){if(d+1>=g)break;c[d++]=192|l>>6}else{if(65535>=l){if(d+2>=g)break;c[d++]=224|l>>12}else{if(d+3>=g)break;c[d++]=240|l>>18;c[d++]=128|l>>12&63}c[d++]=128|
l>>6&63}c[d++]=128|l&63}}c[d]=0}return c}
function Ya(b,c,d,g){function h(f,t,u){for(f="number"==typeof f?f.toString():f||"";f.length<t;)f=u[0]+f;return f}function l(f,t){return h(f,t,"0")}function T(f,t){function u(Pa){return 0>Pa?-1:0<Pa?1:0}var Y;0===(Y=u(f.getFullYear()-t.getFullYear()))&&0===(Y=u(f.getMonth()-t.getMonth()))&&(Y=u(f.getDate()-t.getDate()));return Y}function ia(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function ba(f){var t=f.Ad;for(f=new Date((new Date(f.Bd+1900,0,1)).getTime());0<t;){var u=f.getMonth(),Y=(Ua(f.getFullYear())?Va:Wa)[u];if(t>Y-f.getDate())t-=Y-f.getDate()+1,f.setDate(1),11>u?f.setMonth(u+1):(f.setMonth(0),f.setFullYear(f.getFullYear()+1));else{f.setDate(f.getDate()+t);break}}u=new Date(f.getFullYear()+1,0,4);t=ia(new Date(f.getFullYear(),
0,4));u=ia(u);return 0>=T(t,f)?0>=T(u,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var M=m[g+40>>2];g={Le:m[g>>2],Ke:m[g+4>>2],Ed:m[g+8>>2],Gd:m[g+12>>2],Fd:m[g+16>>2],Bd:m[g+20>>2],zd:m[g+24>>2],Ad:m[g+28>>2],Re:m[g+32>>2],Je:m[g+36>>2],Me:M?wa(M):""};d=wa(d);M={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y",
"%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var F in M)d=d.replace(new RegExp(F,"g"),M[F]);var Qa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Ra="January February March April May June July August September October November December".split(" ");M={"%a":function(f){return Qa[f.zd].substring(0,3)},"%A":function(f){return Qa[f.zd]},"%b":function(f){return Ra[f.Fd].substring(0,
3)},"%B":function(f){return Ra[f.Fd]},"%C":function(f){return l((f.Bd+1900)/100|0,2)},"%d":function(f){return l(f.Gd,2)},"%e":function(f){return h(f.Gd,2," ")},"%g":function(f){return ba(f).toString().substring(2)},"%G":function(f){return ba(f)},"%H":function(f){return l(f.Ed,2)},"%I":function(f){f=f.Ed;0==f?f=12:12<f&&(f-=12);return l(f,2)},"%j":function(f){for(var t=0,u=0;u<=f.Fd-1;t+=(Ua(f.Bd+1900)?Va:Wa)[u++]);return l(f.Gd+t,3)},"%m":function(f){return l(f.Fd+1,2)},"%M":function(f){return l(f.Ke,
2)},"%n":function(){return"\n"},"%p":function(f){return 0<=f.Ed&&12>f.Ed?"AM":"PM"},"%S":function(f){return l(f.Le,2)},"%t":function(){return"\t"},"%u":function(f){return f.zd||7},"%U":function(f){return l(Math.floor((f.Ad+7-f.zd)/7),2)},"%V":function(f){var t=Math.floor((f.Ad+7-(f.zd+6)%7)/7);2>=(f.zd+371-f.Ad-2)%7&&t++;if(t)53==t&&(u=(f.zd+371-f.Ad)%7,4==u||3==u&&Ua(f.Bd)||(t=1));else{t=52;var u=(f.zd+7-f.Ad-1)%7;(4==u||5==u&&Ua(f.Bd%400-1))&&t++}return l(t,2)},"%w":function(f){return f.zd},"%W":function(f){return l(Math.floor((f.Ad+
7-(f.zd+6)%7)/7),2)},"%y":function(f){return(f.Bd+1900).toString().substring(2)},"%Y":function(f){return f.Bd+1900},"%z":function(f){f=f.Je;var t=0<=f;f=Math.abs(f)/60;return(t?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.Me},"%%":function(){return"%"}};d=d.replace(/%%/g,"\x00\x00");for(F in M)d.includes(F)&&(d=d.replace(new RegExp(F,"g"),M[F](g)));d=d.replace(/\0\0/g,"%");F=Xa(d);if(F.length>c)return 0;ya.set(F,b);return F.length-1}
var $a={b:function(b){return Za(b+24)+24},a:function(b,c,d){(new La(b)).Ne(c,d);Ma++;throw b;},d:function(){ra("")},l:function(){return xa.length},e:ja?()=>{var b=process.hrtime();return 1E3*b[0]+b[1]/1E6}:()=>performance.now(),j:function(b,c,d){xa.copyWithin(b,c,c+d)},i:function(){ra("OOM")},n:function(b,c){var d=0;Oa().forEach(function(g,h){var l=c+d;h=n[b+4*h>>2]=l;for(l=0;l<g.length;++l)ya[h++>>0]=g.charCodeAt(l);ya[h>>0]=0;d+=g.length+1});return 0},f:function(b,c){var d=Oa();n[b>>2]=d.length;
var g=0;d.forEach(function(h){g+=h.length+1});n[c>>2]=g;return 0},g:function(){return 52},h:function(){return 52},k:function(){return 70},c:function(b,c,d,g){for(var h=0,l=0;l<d;l++){var T=n[c>>2],ia=n[c+4>>2];c+=8;for(var ba=0;ba<ia;ba++){var M=xa[T+ba],F=Ta[b];0===M||10===M?((1===b?pa:k)(va(F,0)),F.length=0):F.push(M)}h+=ia}n[g>>2]=h;return 0},m:function(b,c,d,g){return Ya(b,c,d,g)}};
(function(){function b(h){a.asm=h.exports;sa=a.asm.o;h=sa.buffer;a.HEAP8=ya=new Int8Array(h);a.HEAP16=new Int16Array(h);a.HEAP32=m=new Int32Array(h);a.HEAPU8=xa=new Uint8Array(h);a.HEAPU16=new Uint16Array(h);a.HEAPU32=n=new Uint32Array(h);a.HEAPF32=new Float32Array(h);a.HEAPF64=new Float64Array(h);Aa.unshift(a.asm.p);p--;a.monitorRunDependencies&&a.monitorRunDependencies(p);0==p&&(null!==Ea&&(clearInterval(Ea),Ea=null),Fa&&(h=Fa,Fa=null,h()))}function c(h){b(h.instance)}function d(h){return Ja().then(function(l){return WebAssembly.instantiate(l,
g)}).then(function(l){return l}).then(h,function(l){k("failed to asynchronously prepare wasm: "+l);ra(l)})}var g={a:$a};p++;a.monitorRunDependencies&&a.monitorRunDependencies(p);if(a.instantiateWasm)try{return a.instantiateWasm(g,b)}catch(h){return k("Module.instantiateWasm callback failed with error: "+h),!1}(function(){return qa||"function"!=typeof WebAssembly.instantiateStreaming||Ga()||q.startsWith("file://")||ja||"function"!=typeof fetch?d(c):fetch(q,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,
g).then(c,function(l){k("wasm streaming compile failed: "+l);k("falling back to ArrayBuffer instantiation");return d(c)})})})().catch(ca);return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.p).apply(null,arguments)};
var ab=a._emscripten_bind_ShapeSettings_Create_0=function(){return(ab=a._emscripten_bind_ShapeSettings_Create_0=a.asm.q).apply(null,arguments)},bb=a._emscripten_bind_ShapeSettings_get_mUserData_0=function(){return(bb=a._emscripten_bind_ShapeSettings_get_mUserData_0=a.asm.r).apply(null,arguments)},cb=a._emscripten_bind_ShapeSettings_set_mUserData_1=function(){return(cb=a._emscripten_bind_ShapeSettings_set_mUserData_1=a.asm.s).apply(null,arguments)},db=a._emscripten_bind_ShapeSettings___destroy___0=
function(){return(db=a._emscripten_bind_ShapeSettings___destroy___0=a.asm.t).apply(null,arguments)},eb=a._emscripten_bind_Shape_GetType_0=function(){return(eb=a._emscripten_bind_Shape_GetType_0=a.asm.u).apply(null,arguments)},fb=a._emscripten_bind_Shape_GetSubType_0=function(){return(fb=a._emscripten_bind_Shape_GetSubType_0=a.asm.v).apply(null,arguments)},gb=a._emscripten_bind_Shape_MustBeStatic_0=function(){return(gb=a._emscripten_bind_Shape_MustBeStatic_0=a.asm.w).apply(null,arguments)},hb=a._emscripten_bind_Shape_GetLocalBounds_0=
function(){return(hb=a._emscripten_bind_Shape_GetLocalBounds_0=a.asm.x).apply(null,arguments)},ib=a._emscripten_bind_Shape_GetWorldSpaceBounds_2=function(){return(ib=a._emscripten_bind_Shape_GetWorldSpaceBounds_2=a.asm.y).apply(null,arguments)},jb=a._emscripten_bind_Shape_GetCenterOfMass_0=function(){return(jb=a._emscripten_bind_Shape_GetCenterOfMass_0=a.asm.z).apply(null,arguments)},kb=a._emscripten_bind_Shape_GetUserData_0=function(){return(kb=a._emscripten_bind_Shape_GetUserData_0=a.asm.A).apply(null,
arguments)},lb=a._emscripten_bind_Shape_SetUserData_1=function(){return(lb=a._emscripten_bind_Shape_SetUserData_1=a.asm.B).apply(null,arguments)},mb=a._emscripten_bind_Shape___destroy___0=function(){return(mb=a._emscripten_bind_Shape___destroy___0=a.asm.C).apply(null,arguments)},nb=a._emscripten_bind_VoidPtr___destroy___0=function(){return(nb=a._emscripten_bind_VoidPtr___destroy___0=a.asm.D).apply(null,arguments)},ob=a._emscripten_bind_JPHString_c_str_0=function(){return(ob=a._emscripten_bind_JPHString_c_str_0=
a.asm.E).apply(null,arguments)},pb=a._emscripten_bind_JPHString___destroy___0=function(){return(pb=a._emscripten_bind_JPHString___destroy___0=a.asm.F).apply(null,arguments)},qb=a._emscripten_bind_ArrayVec3_size_0=function(){return(qb=a._emscripten_bind_ArrayVec3_size_0=a.asm.G).apply(null,arguments)},rb=a._emscripten_bind_ArrayVec3_at_1=function(){return(rb=a._emscripten_bind_ArrayVec3_at_1=a.asm.H).apply(null,arguments)},sb=a._emscripten_bind_ArrayVec3_push_back_1=function(){return(sb=a._emscripten_bind_ArrayVec3_push_back_1=
a.asm.I).apply(null,arguments)},tb=a._emscripten_bind_ArrayVec3___destroy___0=function(){return(tb=a._emscripten_bind_ArrayVec3___destroy___0=a.asm.J).apply(null,arguments)},ub=a._emscripten_bind_Vec3_Vec3_0=function(){return(ub=a._emscripten_bind_Vec3_Vec3_0=a.asm.K).apply(null,arguments)},vb=a._emscripten_bind_Vec3_Vec3_3=function(){return(vb=a._emscripten_bind_Vec3_Vec3_3=a.asm.L).apply(null,arguments)},wb=a._emscripten_bind_Vec3_sZero_0=function(){return(wb=a._emscripten_bind_Vec3_sZero_0=a.asm.M).apply(null,
arguments)},xb=a._emscripten_bind_Vec3_Length_0=function(){return(xb=a._emscripten_bind_Vec3_Length_0=a.asm.N).apply(null,arguments)},yb=a._emscripten_bind_Vec3_GetX_0=function(){return(yb=a._emscripten_bind_Vec3_GetX_0=a.asm.O).apply(null,arguments)},zb=a._emscripten_bind_Vec3_GetY_0=function(){return(zb=a._emscripten_bind_Vec3_GetY_0=a.asm.P).apply(null,arguments)},Ab=a._emscripten_bind_Vec3_GetZ_0=function(){return(Ab=a._emscripten_bind_Vec3_GetZ_0=a.asm.Q).apply(null,arguments)},Bb=a._emscripten_bind_Vec3_SetX_1=
function(){return(Bb=a._emscripten_bind_Vec3_SetX_1=a.asm.R).apply(null,arguments)},Cb=a._emscripten_bind_Vec3_SetY_1=function(){return(Cb=a._emscripten_bind_Vec3_SetY_1=a.asm.S).apply(null,arguments)},Db=a._emscripten_bind_Vec3_SetZ_1=function(){return(Db=a._emscripten_bind_Vec3_SetZ_1=a.asm.T).apply(null,arguments)},Eb=a._emscripten_bind_Vec3___destroy___0=function(){return(Eb=a._emscripten_bind_Vec3___destroy___0=a.asm.U).apply(null,arguments)},Fb=a._emscripten_bind_Quat_Quat_0=function(){return(Fb=
a._emscripten_bind_Quat_Quat_0=a.asm.V).apply(null,arguments)},Gb=a._emscripten_bind_Quat_Quat_4=function(){return(Gb=a._emscripten_bind_Quat_Quat_4=a.asm.W).apply(null,arguments)},Hb=a._emscripten_bind_Quat_sIdentity_0=function(){return(Hb=a._emscripten_bind_Quat_sIdentity_0=a.asm.X).apply(null,arguments)},Ib=a._emscripten_bind_Quat_Length_0=function(){return(Ib=a._emscripten_bind_Quat_Length_0=a.asm.Y).apply(null,arguments)},Jb=a._emscripten_bind_Quat_GetX_0=function(){return(Jb=a._emscripten_bind_Quat_GetX_0=
a.asm.Z).apply(null,arguments)},Kb=a._emscripten_bind_Quat_GetY_0=function(){return(Kb=a._emscripten_bind_Quat_GetY_0=a.asm._).apply(null,arguments)},Lb=a._emscripten_bind_Quat_GetZ_0=function(){return(Lb=a._emscripten_bind_Quat_GetZ_0=a.asm.$).apply(null,arguments)},Mb=a._emscripten_bind_Quat_GetW_0=function(){return(Mb=a._emscripten_bind_Quat_GetW_0=a.asm.aa).apply(null,arguments)},Nb=a._emscripten_bind_Quat___destroy___0=function(){return(Nb=a._emscripten_bind_Quat___destroy___0=a.asm.ba).apply(null,
arguments)},Ob=a._emscripten_bind_Float3_Float3_3=function(){return(Ob=a._emscripten_bind_Float3_Float3_3=a.asm.ca).apply(null,arguments)},Pb=a._emscripten_bind_Float3_get_x_0=function(){return(Pb=a._emscripten_bind_Float3_get_x_0=a.asm.da).apply(null,arguments)},Qb=a._emscripten_bind_Float3_set_x_1=function(){return(Qb=a._emscripten_bind_Float3_set_x_1=a.asm.ea).apply(null,arguments)},Rb=a._emscripten_bind_Float3_get_y_0=function(){return(Rb=a._emscripten_bind_Float3_get_y_0=a.asm.fa).apply(null,
arguments)},Sb=a._emscripten_bind_Float3_set_y_1=function(){return(Sb=a._emscripten_bind_Float3_set_y_1=a.asm.ga).apply(null,arguments)},Tb=a._emscripten_bind_Float3_get_z_0=function(){return(Tb=a._emscripten_bind_Float3_get_z_0=a.asm.ha).apply(null,arguments)},Ub=a._emscripten_bind_Float3_set_z_1=function(){return(Ub=a._emscripten_bind_Float3_set_z_1=a.asm.ia).apply(null,arguments)},Vb=a._emscripten_bind_Float3___destroy___0=function(){return(Vb=a._emscripten_bind_Float3___destroy___0=a.asm.ja).apply(null,
arguments)},Wb=a._emscripten_bind_Mat44_sRotationTranslation_2=function(){return(Wb=a._emscripten_bind_Mat44_sRotationTranslation_2=a.asm.ka).apply(null,arguments)},Xb=a._emscripten_bind_Mat44_GetAxisX_0=function(){return(Xb=a._emscripten_bind_Mat44_GetAxisX_0=a.asm.la).apply(null,arguments)},Yb=a._emscripten_bind_Mat44_GetAxisY_0=function(){return(Yb=a._emscripten_bind_Mat44_GetAxisY_0=a.asm.ma).apply(null,arguments)},Zb=a._emscripten_bind_Mat44_GetAxisZ_0=function(){return(Zb=a._emscripten_bind_Mat44_GetAxisZ_0=
a.asm.na).apply(null,arguments)},$b=a._emscripten_bind_Mat44_GetQuaternion_0=function(){return($b=a._emscripten_bind_Mat44_GetQuaternion_0=a.asm.oa).apply(null,arguments)},ac=a._emscripten_bind_Mat44_GetTranslation_0=function(){return(ac=a._emscripten_bind_Mat44_GetTranslation_0=a.asm.pa).apply(null,arguments)},bc=a._emscripten_bind_Mat44___destroy___0=function(){return(bc=a._emscripten_bind_Mat44___destroy___0=a.asm.qa).apply(null,arguments)},cc=a._emscripten_bind_AABox_AABox_2=function(){return(cc=
a._emscripten_bind_AABox_AABox_2=a.asm.ra).apply(null,arguments)},dc=a._emscripten_bind_AABox_sBiggest_0=function(){return(dc=a._emscripten_bind_AABox_sBiggest_0=a.asm.sa).apply(null,arguments)},ec=a._emscripten_bind_AABox_get_mMin_0=function(){return(ec=a._emscripten_bind_AABox_get_mMin_0=a.asm.ta).apply(null,arguments)},fc=a._emscripten_bind_AABox_set_mMin_1=function(){return(fc=a._emscripten_bind_AABox_set_mMin_1=a.asm.ua).apply(null,arguments)},gc=a._emscripten_bind_AABox_get_mMax_0=function(){return(gc=
a._emscripten_bind_AABox_get_mMax_0=a.asm.va).apply(null,arguments)},hc=a._emscripten_bind_AABox_set_mMax_1=function(){return(hc=a._emscripten_bind_AABox_set_mMax_1=a.asm.wa).apply(null,arguments)},ic=a._emscripten_bind_AABox___destroy___0=function(){return(ic=a._emscripten_bind_AABox___destroy___0=a.asm.xa).apply(null,arguments)},jc=a._emscripten_bind_PhysicsMaterial___destroy___0=function(){return(jc=a._emscripten_bind_PhysicsMaterial___destroy___0=a.asm.ya).apply(null,arguments)},kc=a._emscripten_bind_GetTrianglesContext___destroy___0=
function(){return(kc=a._emscripten_bind_GetTrianglesContext___destroy___0=a.asm.za).apply(null,arguments)},lc=a._emscripten_bind_ShapeResult_IsValid_0=function(){return(lc=a._emscripten_bind_ShapeResult_IsValid_0=a.asm.Aa).apply(null,arguments)},mc=a._emscripten_bind_ShapeResult_HasError_0=function(){return(mc=a._emscripten_bind_ShapeResult_HasError_0=a.asm.Ba).apply(null,arguments)},nc=a._emscripten_bind_ShapeResult_GetError_0=function(){return(nc=a._emscripten_bind_ShapeResult_GetError_0=a.asm.Ca).apply(null,
arguments)},oc=a._emscripten_bind_ShapeResult_Get_0=function(){return(oc=a._emscripten_bind_ShapeResult_Get_0=a.asm.Da).apply(null,arguments)},pc=a._emscripten_bind_ShapeResult___destroy___0=function(){return(pc=a._emscripten_bind_ShapeResult___destroy___0=a.asm.Ea).apply(null,arguments)},qc=a._emscripten_bind_ShapeGetTriangles_ShapeGetTriangles_5=function(){return(qc=a._emscripten_bind_ShapeGetTriangles_ShapeGetTriangles_5=a.asm.Fa).apply(null,arguments)},rc=a._emscripten_bind_ShapeGetTriangles_GetNumTriangles_0=
function(){return(rc=a._emscripten_bind_ShapeGetTriangles_GetNumTriangles_0=a.asm.Ga).apply(null,arguments)},sc=a._emscripten_bind_ShapeGetTriangles_GetVertices_4=function(){return(sc=a._emscripten_bind_ShapeGetTriangles_GetVertices_4=a.asm.Ha).apply(null,arguments)},tc=a._emscripten_bind_ShapeGetTriangles_GetMaterial_1=function(){return(tc=a._emscripten_bind_ShapeGetTriangles_GetMaterial_1=a.asm.Ia).apply(null,arguments)},uc=a._emscripten_bind_ShapeGetTriangles___destroy___0=function(){return(uc=
a._emscripten_bind_ShapeGetTriangles___destroy___0=a.asm.Ja).apply(null,arguments)},vc=a._emscripten_bind_SphereShape_SphereShape_2=function(){return(vc=a._emscripten_bind_SphereShape_SphereShape_2=a.asm.Ka).apply(null,arguments)},wc=a._emscripten_bind_SphereShape_GetType_0=function(){return(wc=a._emscripten_bind_SphereShape_GetType_0=a.asm.La).apply(null,arguments)},xc=a._emscripten_bind_SphereShape_GetSubType_0=function(){return(xc=a._emscripten_bind_SphereShape_GetSubType_0=a.asm.Ma).apply(null,
arguments)},yc=a._emscripten_bind_SphereShape_MustBeStatic_0=function(){return(yc=a._emscripten_bind_SphereShape_MustBeStatic_0=a.asm.Na).apply(null,arguments)},zc=a._emscripten_bind_SphereShape_GetLocalBounds_0=function(){return(zc=a._emscripten_bind_SphereShape_GetLocalBounds_0=a.asm.Oa).apply(null,arguments)},Ac=a._emscripten_bind_SphereShape_GetWorldSpaceBounds_2=function(){return(Ac=a._emscripten_bind_SphereShape_GetWorldSpaceBounds_2=a.asm.Pa).apply(null,arguments)},Bc=a._emscripten_bind_SphereShape_GetCenterOfMass_0=
function(){return(Bc=a._emscripten_bind_SphereShape_GetCenterOfMass_0=a.asm.Qa).apply(null,arguments)},Cc=a._emscripten_bind_SphereShape_GetUserData_0=function(){return(Cc=a._emscripten_bind_SphereShape_GetUserData_0=a.asm.Ra).apply(null,arguments)},Dc=a._emscripten_bind_SphereShape_SetUserData_1=function(){return(Dc=a._emscripten_bind_SphereShape_SetUserData_1=a.asm.Sa).apply(null,arguments)},Ec=a._emscripten_bind_SphereShape___destroy___0=function(){return(Ec=a._emscripten_bind_SphereShape___destroy___0=
a.asm.Ta).apply(null,arguments)},Fc=a._emscripten_bind_BoxShape_BoxShape_3=function(){return(Fc=a._emscripten_bind_BoxShape_BoxShape_3=a.asm.Ua).apply(null,arguments)},Gc=a._emscripten_bind_BoxShape_GetType_0=function(){return(Gc=a._emscripten_bind_BoxShape_GetType_0=a.asm.Va).apply(null,arguments)},Hc=a._emscripten_bind_BoxShape_GetSubType_0=function(){return(Hc=a._emscripten_bind_BoxShape_GetSubType_0=a.asm.Wa).apply(null,arguments)},Ic=a._emscripten_bind_BoxShape_MustBeStatic_0=function(){return(Ic=
a._emscripten_bind_BoxShape_MustBeStatic_0=a.asm.Xa).apply(null,arguments)},Jc=a._emscripten_bind_BoxShape_GetLocalBounds_0=function(){return(Jc=a._emscripten_bind_BoxShape_GetLocalBounds_0=a.asm.Ya).apply(null,arguments)},Kc=a._emscripten_bind_BoxShape_GetWorldSpaceBounds_2=function(){return(Kc=a._emscripten_bind_BoxShape_GetWorldSpaceBounds_2=a.asm.Za).apply(null,arguments)},Lc=a._emscripten_bind_BoxShape_GetCenterOfMass_0=function(){return(Lc=a._emscripten_bind_BoxShape_GetCenterOfMass_0=a.asm._a).apply(null,
arguments)},Mc=a._emscripten_bind_BoxShape_GetUserData_0=function(){return(Mc=a._emscripten_bind_BoxShape_GetUserData_0=a.asm.$a).apply(null,arguments)},Nc=a._emscripten_bind_BoxShape_SetUserData_1=function(){return(Nc=a._emscripten_bind_BoxShape_SetUserData_1=a.asm.ab).apply(null,arguments)},Oc=a._emscripten_bind_BoxShape___destroy___0=function(){return(Oc=a._emscripten_bind_BoxShape___destroy___0=a.asm.bb).apply(null,arguments)},Pc=a._emscripten_bind_CylinderShape_CylinderShape_4=function(){return(Pc=
a._emscripten_bind_CylinderShape_CylinderShape_4=a.asm.cb).apply(null,arguments)},Qc=a._emscripten_bind_CylinderShape_GetType_0=function(){return(Qc=a._emscripten_bind_CylinderShape_GetType_0=a.asm.db).apply(null,arguments)},Rc=a._emscripten_bind_CylinderShape_GetSubType_0=function(){return(Rc=a._emscripten_bind_CylinderShape_GetSubType_0=a.asm.eb).apply(null,arguments)},Sc=a._emscripten_bind_CylinderShape_MustBeStatic_0=function(){return(Sc=a._emscripten_bind_CylinderShape_MustBeStatic_0=a.asm.fb).apply(null,
arguments)},Tc=a._emscripten_bind_CylinderShape_GetLocalBounds_0=function(){return(Tc=a._emscripten_bind_CylinderShape_GetLocalBounds_0=a.asm.gb).apply(null,arguments)},Uc=a._emscripten_bind_CylinderShape_GetWorldSpaceBounds_2=function(){return(Uc=a._emscripten_bind_CylinderShape_GetWorldSpaceBounds_2=a.asm.hb).apply(null,arguments)},Vc=a._emscripten_bind_CylinderShape_GetCenterOfMass_0=function(){return(Vc=a._emscripten_bind_CylinderShape_GetCenterOfMass_0=a.asm.ib).apply(null,arguments)},Wc=a._emscripten_bind_CylinderShape_GetUserData_0=
function(){return(Wc=a._emscripten_bind_CylinderShape_GetUserData_0=a.asm.jb).apply(null,arguments)},Xc=a._emscripten_bind_CylinderShape_SetUserData_1=function(){return(Xc=a._emscripten_bind_CylinderShape_SetUserData_1=a.asm.kb).apply(null,arguments)},Yc=a._emscripten_bind_CylinderShape___destroy___0=function(){return(Yc=a._emscripten_bind_CylinderShape___destroy___0=a.asm.lb).apply(null,arguments)},Zc=a._emscripten_bind_CapsuleShape_CapsuleShape_3=function(){return(Zc=a._emscripten_bind_CapsuleShape_CapsuleShape_3=
a.asm.mb).apply(null,arguments)},$c=a._emscripten_bind_CapsuleShape_GetType_0=function(){return($c=a._emscripten_bind_CapsuleShape_GetType_0=a.asm.nb).apply(null,arguments)},ad=a._emscripten_bind_CapsuleShape_GetSubType_0=function(){return(ad=a._emscripten_bind_CapsuleShape_GetSubType_0=a.asm.ob).apply(null,arguments)},bd=a._emscripten_bind_CapsuleShape_MustBeStatic_0=function(){return(bd=a._emscripten_bind_CapsuleShape_MustBeStatic_0=a.asm.pb).apply(null,arguments)},cd=a._emscripten_bind_CapsuleShape_GetLocalBounds_0=
function(){return(cd=a._emscripten_bind_CapsuleShape_GetLocalBounds_0=a.asm.qb).apply(null,arguments)},dd=a._emscripten_bind_CapsuleShape_GetWorldSpaceBounds_2=function(){return(dd=a._emscripten_bind_CapsuleShape_GetWorldSpaceBounds_2=a.asm.rb).apply(null,arguments)},ed=a._emscripten_bind_CapsuleShape_GetCenterOfMass_0=function(){return(ed=a._emscripten_bind_CapsuleShape_GetCenterOfMass_0=a.asm.sb).apply(null,arguments)},fd=a._emscripten_bind_CapsuleShape_GetUserData_0=function(){return(fd=a._emscripten_bind_CapsuleShape_GetUserData_0=
a.asm.tb).apply(null,arguments)},gd=a._emscripten_bind_CapsuleShape_SetUserData_1=function(){return(gd=a._emscripten_bind_CapsuleShape_SetUserData_1=a.asm.ub).apply(null,arguments)},hd=a._emscripten_bind_CapsuleShape___destroy___0=function(){return(hd=a._emscripten_bind_CapsuleShape___destroy___0=a.asm.vb).apply(null,arguments)},jd=a._emscripten_bind_ConvexHullShapeSettings_ConvexHullShapeSettings_0=function(){return(jd=a._emscripten_bind_ConvexHullShapeSettings_ConvexHullShapeSettings_0=a.asm.wb).apply(null,
arguments)},kd=a._emscripten_bind_ConvexHullShapeSettings_Create_0=function(){return(kd=a._emscripten_bind_ConvexHullShapeSettings_Create_0=a.asm.xb).apply(null,arguments)},ld=a._emscripten_bind_ConvexHullShapeSettings_get_mPoints_0=function(){return(ld=a._emscripten_bind_ConvexHullShapeSettings_get_mPoints_0=a.asm.yb).apply(null,arguments)},md=a._emscripten_bind_ConvexHullShapeSettings_set_mPoints_1=function(){return(md=a._emscripten_bind_ConvexHullShapeSettings_set_mPoints_1=a.asm.zb).apply(null,
arguments)},nd=a._emscripten_bind_ConvexHullShapeSettings_get_mMaxConvexRadius_0=function(){return(nd=a._emscripten_bind_ConvexHullShapeSettings_get_mMaxConvexRadius_0=a.asm.Ab).apply(null,arguments)},od=a._emscripten_bind_ConvexHullShapeSettings_set_mMaxConvexRadius_1=function(){return(od=a._emscripten_bind_ConvexHullShapeSettings_set_mMaxConvexRadius_1=a.asm.Bb).apply(null,arguments)},pd=a._emscripten_bind_ConvexHullShapeSettings_get_mMaxErrorConvexRadius_0=function(){return(pd=a._emscripten_bind_ConvexHullShapeSettings_get_mMaxErrorConvexRadius_0=
a.asm.Cb).apply(null,arguments)},qd=a._emscripten_bind_ConvexHullShapeSettings_set_mMaxErrorConvexRadius_1=function(){return(qd=a._emscripten_bind_ConvexHullShapeSettings_set_mMaxErrorConvexRadius_1=a.asm.Db).apply(null,arguments)},rd=a._emscripten_bind_ConvexHullShapeSettings_get_mHullTolerance_0=function(){return(rd=a._emscripten_bind_ConvexHullShapeSettings_get_mHullTolerance_0=a.asm.Eb).apply(null,arguments)},sd=a._emscripten_bind_ConvexHullShapeSettings_set_mHullTolerance_1=function(){return(sd=
a._emscripten_bind_ConvexHullShapeSettings_set_mHullTolerance_1=a.asm.Fb).apply(null,arguments)},td=a._emscripten_bind_ConvexHullShapeSettings_get_mUserData_0=function(){return(td=a._emscripten_bind_ConvexHullShapeSettings_get_mUserData_0=a.asm.Gb).apply(null,arguments)},ud=a._emscripten_bind_ConvexHullShapeSettings_set_mUserData_1=function(){return(ud=a._emscripten_bind_ConvexHullShapeSettings_set_mUserData_1=a.asm.Hb).apply(null,arguments)},vd=a._emscripten_bind_ConvexHullShapeSettings___destroy___0=
function(){return(vd=a._emscripten_bind_ConvexHullShapeSettings___destroy___0=a.asm.Ib).apply(null,arguments)},wd=a._emscripten_bind_ConvexHullShape_GetType_0=function(){return(wd=a._emscripten_bind_ConvexHullShape_GetType_0=a.asm.Jb).apply(null,arguments)},xd=a._emscripten_bind_ConvexHullShape_GetSubType_0=function(){return(xd=a._emscripten_bind_ConvexHullShape_GetSubType_0=a.asm.Kb).apply(null,arguments)},yd=a._emscripten_bind_ConvexHullShape_MustBeStatic_0=function(){return(yd=a._emscripten_bind_ConvexHullShape_MustBeStatic_0=
a.asm.Lb).apply(null,arguments)},zd=a._emscripten_bind_ConvexHullShape_GetLocalBounds_0=function(){return(zd=a._emscripten_bind_ConvexHullShape_GetLocalBounds_0=a.asm.Mb).apply(null,arguments)},Ad=a._emscripten_bind_ConvexHullShape_GetWorldSpaceBounds_2=function(){return(Ad=a._emscripten_bind_ConvexHullShape_GetWorldSpaceBounds_2=a.asm.Nb).apply(null,arguments)},Bd=a._emscripten_bind_ConvexHullShape_GetCenterOfMass_0=function(){return(Bd=a._emscripten_bind_ConvexHullShape_GetCenterOfMass_0=a.asm.Ob).apply(null,
arguments)},Cd=a._emscripten_bind_ConvexHullShape_GetUserData_0=function(){return(Cd=a._emscripten_bind_ConvexHullShape_GetUserData_0=a.asm.Pb).apply(null,arguments)},Dd=a._emscripten_bind_ConvexHullShape_SetUserData_1=function(){return(Dd=a._emscripten_bind_ConvexHullShape_SetUserData_1=a.asm.Qb).apply(null,arguments)},Ed=a._emscripten_bind_ConvexHullShape___destroy___0=function(){return(Ed=a._emscripten_bind_ConvexHullShape___destroy___0=a.asm.Rb).apply(null,arguments)},Fd=a._emscripten_bind_BodyID_BodyID_0=
function(){return(Fd=a._emscripten_bind_BodyID_BodyID_0=a.asm.Sb).apply(null,arguments)},Gd=a._emscripten_bind_BodyID_BodyID_1=function(){return(Gd=a._emscripten_bind_BodyID_BodyID_1=a.asm.Tb).apply(null,arguments)},Hd=a._emscripten_bind_BodyID___destroy___0=function(){return(Hd=a._emscripten_bind_BodyID___destroy___0=a.asm.Ub).apply(null,arguments)},Id=a._emscripten_bind_Body_GetID_0=function(){return(Id=a._emscripten_bind_Body_GetID_0=a.asm.Vb).apply(null,arguments)},Jd=a._emscripten_bind_Body_GetPosition_0=
function(){return(Jd=a._emscripten_bind_Body_GetPosition_0=a.asm.Wb).apply(null,arguments)},Kd=a._emscripten_bind_Body_GetRotation_0=function(){return(Kd=a._emscripten_bind_Body_GetRotation_0=a.asm.Xb).apply(null,arguments)},Ld=a._emscripten_bind_Body___destroy___0=function(){return(Ld=a._emscripten_bind_Body___destroy___0=a.asm.Yb).apply(null,arguments)},Md=a._emscripten_bind_BodyInterface_CreateBody_1=function(){return(Md=a._emscripten_bind_BodyInterface_CreateBody_1=a.asm.Zb).apply(null,arguments)},
Nd=a._emscripten_bind_BodyInterface_AddBody_2=function(){return(Nd=a._emscripten_bind_BodyInterface_AddBody_2=a.asm._b).apply(null,arguments)},Od=a._emscripten_bind_BodyInterface_CreateAndAddBody_2=function(){return(Od=a._emscripten_bind_BodyInterface_CreateAndAddBody_2=a.asm.$b).apply(null,arguments)},Pd=a._emscripten_bind_BodyInterface_GetPositionAndRotation_3=function(){return(Pd=a._emscripten_bind_BodyInterface_GetPositionAndRotation_3=a.asm.ac).apply(null,arguments)},Qd=a._emscripten_bind_BodyInterface___destroy___0=
function(){return(Qd=a._emscripten_bind_BodyInterface___destroy___0=a.asm.bc).apply(null,arguments)},Rd=a._emscripten_bind_PhysicsSystem_GetBodyInterface_0=function(){return(Rd=a._emscripten_bind_PhysicsSystem_GetBodyInterface_0=a.asm.cc).apply(null,arguments)},Sd=a._emscripten_bind_PhysicsSystem___destroy___0=function(){return(Sd=a._emscripten_bind_PhysicsSystem___destroy___0=a.asm.dc).apply(null,arguments)},Td=a._emscripten_bind_BodyCreationSettings_BodyCreationSettings_5=function(){return(Td=a._emscripten_bind_BodyCreationSettings_BodyCreationSettings_5=
a.asm.ec).apply(null,arguments)},Ud=a._emscripten_bind_BodyCreationSettings_get_mPosition_0=function(){return(Ud=a._emscripten_bind_BodyCreationSettings_get_mPosition_0=a.asm.fc).apply(null,arguments)},Vd=a._emscripten_bind_BodyCreationSettings_set_mPosition_1=function(){return(Vd=a._emscripten_bind_BodyCreationSettings_set_mPosition_1=a.asm.gc).apply(null,arguments)},Wd=a._emscripten_bind_BodyCreationSettings_get_mRotation_0=function(){return(Wd=a._emscripten_bind_BodyCreationSettings_get_mRotation_0=
a.asm.hc).apply(null,arguments)},Xd=a._emscripten_bind_BodyCreationSettings_set_mRotation_1=function(){return(Xd=a._emscripten_bind_BodyCreationSettings_set_mRotation_1=a.asm.ic).apply(null,arguments)},Yd=a._emscripten_bind_BodyCreationSettings_get_mLinearVelocity_0=function(){return(Yd=a._emscripten_bind_BodyCreationSettings_get_mLinearVelocity_0=a.asm.jc).apply(null,arguments)},Zd=a._emscripten_bind_BodyCreationSettings_set_mLinearVelocity_1=function(){return(Zd=a._emscripten_bind_BodyCreationSettings_set_mLinearVelocity_1=
a.asm.kc).apply(null,arguments)},$d=a._emscripten_bind_BodyCreationSettings_get_mAngularVelocity_0=function(){return($d=a._emscripten_bind_BodyCreationSettings_get_mAngularVelocity_0=a.asm.lc).apply(null,arguments)},ae=a._emscripten_bind_BodyCreationSettings_set_mAngularVelocity_1=function(){return(ae=a._emscripten_bind_BodyCreationSettings_set_mAngularVelocity_1=a.asm.mc).apply(null,arguments)},be=a._emscripten_bind_BodyCreationSettings_get_mUserData_0=function(){return(be=a._emscripten_bind_BodyCreationSettings_get_mUserData_0=
a.asm.nc).apply(null,arguments)},ce=a._emscripten_bind_BodyCreationSettings_set_mUserData_1=function(){return(ce=a._emscripten_bind_BodyCreationSettings_set_mUserData_1=a.asm.oc).apply(null,arguments)},de=a._emscripten_bind_BodyCreationSettings_get_mObjectLayer_0=function(){return(de=a._emscripten_bind_BodyCreationSettings_get_mObjectLayer_0=a.asm.pc).apply(null,arguments)},ee=a._emscripten_bind_BodyCreationSettings_set_mObjectLayer_1=function(){return(ee=a._emscripten_bind_BodyCreationSettings_set_mObjectLayer_1=
a.asm.qc).apply(null,arguments)},fe=a._emscripten_bind_BodyCreationSettings_get_mMotionType_0=function(){return(fe=a._emscripten_bind_BodyCreationSettings_get_mMotionType_0=a.asm.rc).apply(null,arguments)},ge=a._emscripten_bind_BodyCreationSettings_set_mMotionType_1=function(){return(ge=a._emscripten_bind_BodyCreationSettings_set_mMotionType_1=a.asm.sc).apply(null,arguments)},he=a._emscripten_bind_BodyCreationSettings_get_mAllowDynamicOrKinematic_0=function(){return(he=a._emscripten_bind_BodyCreationSettings_get_mAllowDynamicOrKinematic_0=
a.asm.tc).apply(null,arguments)},ie=a._emscripten_bind_BodyCreationSettings_set_mAllowDynamicOrKinematic_1=function(){return(ie=a._emscripten_bind_BodyCreationSettings_set_mAllowDynamicOrKinematic_1=a.asm.uc).apply(null,arguments)},je=a._emscripten_bind_BodyCreationSettings_get_mIsSensor_0=function(){return(je=a._emscripten_bind_BodyCreationSettings_get_mIsSensor_0=a.asm.vc).apply(null,arguments)},ke=a._emscripten_bind_BodyCreationSettings_set_mIsSensor_1=function(){return(ke=a._emscripten_bind_BodyCreationSettings_set_mIsSensor_1=
a.asm.wc).apply(null,arguments)},le=a._emscripten_bind_BodyCreationSettings_get_mMotionQuality_0=function(){return(le=a._emscripten_bind_BodyCreationSettings_get_mMotionQuality_0=a.asm.xc).apply(null,arguments)},me=a._emscripten_bind_BodyCreationSettings_set_mMotionQuality_1=function(){return(me=a._emscripten_bind_BodyCreationSettings_set_mMotionQuality_1=a.asm.yc).apply(null,arguments)},ne=a._emscripten_bind_BodyCreationSettings_get_mAllowSleeping_0=function(){return(ne=a._emscripten_bind_BodyCreationSettings_get_mAllowSleeping_0=
a.asm.zc).apply(null,arguments)},oe=a._emscripten_bind_BodyCreationSettings_set_mAllowSleeping_1=function(){return(oe=a._emscripten_bind_BodyCreationSettings_set_mAllowSleeping_1=a.asm.Ac).apply(null,arguments)},pe=a._emscripten_bind_BodyCreationSettings_get_mFriction_0=function(){return(pe=a._emscripten_bind_BodyCreationSettings_get_mFriction_0=a.asm.Bc).apply(null,arguments)},qe=a._emscripten_bind_BodyCreationSettings_set_mFriction_1=function(){return(qe=a._emscripten_bind_BodyCreationSettings_set_mFriction_1=
a.asm.Cc).apply(null,arguments)},re=a._emscripten_bind_BodyCreationSettings_get_mRestitution_0=function(){return(re=a._emscripten_bind_BodyCreationSettings_get_mRestitution_0=a.asm.Dc).apply(null,arguments)},se=a._emscripten_bind_BodyCreationSettings_set_mRestitution_1=function(){return(se=a._emscripten_bind_BodyCreationSettings_set_mRestitution_1=a.asm.Ec).apply(null,arguments)},te=a._emscripten_bind_BodyCreationSettings_get_mLinearDamping_0=function(){return(te=a._emscripten_bind_BodyCreationSettings_get_mLinearDamping_0=
a.asm.Fc).apply(null,arguments)},ue=a._emscripten_bind_BodyCreationSettings_set_mLinearDamping_1=function(){return(ue=a._emscripten_bind_BodyCreationSettings_set_mLinearDamping_1=a.asm.Gc).apply(null,arguments)},ve=a._emscripten_bind_BodyCreationSettings_get_mAngularDamping_0=function(){return(ve=a._emscripten_bind_BodyCreationSettings_get_mAngularDamping_0=a.asm.Hc).apply(null,arguments)},we=a._emscripten_bind_BodyCreationSettings_set_mAngularDamping_1=function(){return(we=a._emscripten_bind_BodyCreationSettings_set_mAngularDamping_1=
a.asm.Ic).apply(null,arguments)},xe=a._emscripten_bind_BodyCreationSettings_get_mMaxLinearVelocity_0=function(){return(xe=a._emscripten_bind_BodyCreationSettings_get_mMaxLinearVelocity_0=a.asm.Jc).apply(null,arguments)},ye=a._emscripten_bind_BodyCreationSettings_set_mMaxLinearVelocity_1=function(){return(ye=a._emscripten_bind_BodyCreationSettings_set_mMaxLinearVelocity_1=a.asm.Kc).apply(null,arguments)},ze=a._emscripten_bind_BodyCreationSettings_get_mMaxAngularVelocity_0=function(){return(ze=a._emscripten_bind_BodyCreationSettings_get_mMaxAngularVelocity_0=
a.asm.Lc).apply(null,arguments)},Ae=a._emscripten_bind_BodyCreationSettings_set_mMaxAngularVelocity_1=function(){return(Ae=a._emscripten_bind_BodyCreationSettings_set_mMaxAngularVelocity_1=a.asm.Mc).apply(null,arguments)},Be=a._emscripten_bind_BodyCreationSettings_get_mGravityFactor_0=function(){return(Be=a._emscripten_bind_BodyCreationSettings_get_mGravityFactor_0=a.asm.Nc).apply(null,arguments)},Ce=a._emscripten_bind_BodyCreationSettings_set_mGravityFactor_1=function(){return(Ce=a._emscripten_bind_BodyCreationSettings_set_mGravityFactor_1=
a.asm.Oc).apply(null,arguments)},De=a._emscripten_bind_BodyCreationSettings___destroy___0=function(){return(De=a._emscripten_bind_BodyCreationSettings___destroy___0=a.asm.Pc).apply(null,arguments)},Ee=a._emscripten_bind_JoltInterface_JoltInterface_0=function(){return(Ee=a._emscripten_bind_JoltInterface_JoltInterface_0=a.asm.Qc).apply(null,arguments)},Fe=a._emscripten_bind_JoltInterface_Step_3=function(){return(Fe=a._emscripten_bind_JoltInterface_Step_3=a.asm.Rc).apply(null,arguments)},Ge=a._emscripten_bind_JoltInterface_GetPhysicsSystem_0=
function(){return(Ge=a._emscripten_bind_JoltInterface_GetPhysicsSystem_0=a.asm.Sc).apply(null,arguments)},He=a._emscripten_bind_JoltInterface___destroy___0=function(){return(He=a._emscripten_bind_JoltInterface___destroy___0=a.asm.Tc).apply(null,arguments)},Ie=a._emscripten_enum_Layers_MOVING=function(){return(Ie=a._emscripten_enum_Layers_MOVING=a.asm.Uc).apply(null,arguments)},Je=a._emscripten_enum_Layers_NON_MOVING=function(){return(Je=a._emscripten_enum_Layers_NON_MOVING=a.asm.Vc).apply(null,arguments)},
Ke=a._emscripten_enum_EMotionType_Static=function(){return(Ke=a._emscripten_enum_EMotionType_Static=a.asm.Wc).apply(null,arguments)},Le=a._emscripten_enum_EMotionType_Kinematic=function(){return(Le=a._emscripten_enum_EMotionType_Kinematic=a.asm.Xc).apply(null,arguments)},Me=a._emscripten_enum_EMotionType_Dynamic=function(){return(Me=a._emscripten_enum_EMotionType_Dynamic=a.asm.Yc).apply(null,arguments)},Ne=a._emscripten_enum_EMotionQuality_Discrete=function(){return(Ne=a._emscripten_enum_EMotionQuality_Discrete=
a.asm.Zc).apply(null,arguments)},Oe=a._emscripten_enum_EMotionQuality_LinearCast=function(){return(Oe=a._emscripten_enum_EMotionQuality_LinearCast=a.asm._c).apply(null,arguments)},Pe=a._emscripten_enum_EActivation_Activate=function(){return(Pe=a._emscripten_enum_EActivation_Activate=a.asm.$c).apply(null,arguments)},Qe=a._emscripten_enum_EActivation_DontActivate=function(){return(Qe=a._emscripten_enum_EActivation_DontActivate=a.asm.ad).apply(null,arguments)},Re=a._emscripten_enum_EShapeType_Convex=
function(){return(Re=a._emscripten_enum_EShapeType_Convex=a.asm.bd).apply(null,arguments)},Se=a._emscripten_enum_EShapeType_Compound=function(){return(Se=a._emscripten_enum_EShapeType_Compound=a.asm.cd).apply(null,arguments)},Te=a._emscripten_enum_EShapeType_Decorated=function(){return(Te=a._emscripten_enum_EShapeType_Decorated=a.asm.dd).apply(null,arguments)},Ue=a._emscripten_enum_EShapeType_Mesh=function(){return(Ue=a._emscripten_enum_EShapeType_Mesh=a.asm.ed).apply(null,arguments)},Ve=a._emscripten_enum_EShapeType_HeightField=
function(){return(Ve=a._emscripten_enum_EShapeType_HeightField=a.asm.fd).apply(null,arguments)},We=a._emscripten_enum_EShapeSubType_Sphere=function(){return(We=a._emscripten_enum_EShapeSubType_Sphere=a.asm.gd).apply(null,arguments)},Xe=a._emscripten_enum_EShapeSubType_Box=function(){return(Xe=a._emscripten_enum_EShapeSubType_Box=a.asm.hd).apply(null,arguments)},Ye=a._emscripten_enum_EShapeSubType_Triangle=function(){return(Ye=a._emscripten_enum_EShapeSubType_Triangle=a.asm.id).apply(null,arguments)},
Ze=a._emscripten_enum_EShapeSubType_Capsule=function(){return(Ze=a._emscripten_enum_EShapeSubType_Capsule=a.asm.jd).apply(null,arguments)},$e=a._emscripten_enum_EShapeSubType_TaperedCapsule=function(){return($e=a._emscripten_enum_EShapeSubType_TaperedCapsule=a.asm.kd).apply(null,arguments)},af=a._emscripten_enum_EShapeSubType_Cylinder=function(){return(af=a._emscripten_enum_EShapeSubType_Cylinder=a.asm.ld).apply(null,arguments)},bf=a._emscripten_enum_EShapeSubType_ConvexHull=function(){return(bf=
a._emscripten_enum_EShapeSubType_ConvexHull=a.asm.md).apply(null,arguments)},cf=a._emscripten_enum_EShapeSubType_StaticCompound=function(){return(cf=a._emscripten_enum_EShapeSubType_StaticCompound=a.asm.nd).apply(null,arguments)},df=a._emscripten_enum_EShapeSubType_MutableCompound=function(){return(df=a._emscripten_enum_EShapeSubType_MutableCompound=a.asm.od).apply(null,arguments)},ef=a._emscripten_enum_EShapeSubType_RotatedTranslated=function(){return(ef=a._emscripten_enum_EShapeSubType_RotatedTranslated=
a.asm.pd).apply(null,arguments)},ff=a._emscripten_enum_EShapeSubType_Scaled=function(){return(ff=a._emscripten_enum_EShapeSubType_Scaled=a.asm.qd).apply(null,arguments)},gf=a._emscripten_enum_EShapeSubType_OffsetCenterOfMass=function(){return(gf=a._emscripten_enum_EShapeSubType_OffsetCenterOfMass=a.asm.rd).apply(null,arguments)},hf=a._emscripten_enum_EShapeSubType_Mesh=function(){return(hf=a._emscripten_enum_EShapeSubType_Mesh=a.asm.sd).apply(null,arguments)},jf=a._emscripten_enum_EShapeSubType_HeightField=
function(){return(jf=a._emscripten_enum_EShapeSubType_HeightField=a.asm.td).apply(null,arguments)},Za=a._malloc=function(){return(Za=a._malloc=a.asm.vd).apply(null,arguments)};a.___cxa_is_pointer_type=function(){return(a.___cxa_is_pointer_type=a.asm.wd).apply(null,arguments)};a.___start_em_js=42576;a.___stop_em_js=42674;var kf;Fa=function lf(){kf||mf();kf||(Fa=lf)};
function mf(){function b(){if(!kf&&(kf=!0,a.calledRun=!0,!ta)){Ca=!0;Ka(Aa);aa(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();Ba.unshift(c)}Ka(Ba)}}if(!(0<p)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)Da();Ka(za);0<p||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();mf();function r(){}r.prototype=Object.create(r.prototype);r.prototype.constructor=r;r.prototype.xd=r;r.yd={};a.WrapperObject=r;function v(b){return(b||r).yd}a.getCache=v;function w(b,c){var d=v(c),g=d[b];if(g)return g;g=Object.create((c||r).prototype);g.ud=b;return d[b]=g}a.wrapPointer=w;a.castObject=function(b,c){return w(b.ud,c)};a.NULL=w(0);
a.destroy=function(b){if(!b.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";b.__destroy__();delete v(b.xd)[b.ud]};a.compare=function(b,c){return b.ud===c.ud};a.getPointer=function(b){return b.ud};a.getClass=function(b){return b.xd};function x(){throw"cannot construct a ShapeSettings, no constructor in IDL";}x.prototype=Object.create(r.prototype);x.prototype.constructor=x;x.prototype.xd=x;x.yd={};a.ShapeSettings=x;x.prototype.Create=function(){return w(ab(this.ud),y)};
x.prototype.get_mUserData=x.prototype.Cd=function(){return bb(this.ud)};x.prototype.set_mUserData=x.prototype.Dd=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);cb(c,b)};Object.defineProperty(x.prototype,"mUserData",{get:x.prototype.Cd,set:x.prototype.Dd});x.prototype.__destroy__=function(){db(this.ud)};function z(){throw"cannot construct a Shape, no constructor in IDL";}z.prototype=Object.create(r.prototype);z.prototype.constructor=z;z.prototype.xd=z;z.yd={};a.Shape=z;
z.prototype.GetType=function(){return eb(this.ud)};z.prototype.GetSubType=function(){return fb(this.ud)};z.prototype.MustBeStatic=function(){return!!gb(this.ud)};z.prototype.GetLocalBounds=function(){return w(hb(this.ud),A)};z.prototype.GetWorldSpaceBounds=function(b,c){var d=this.ud;b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);return w(ib(d,b,c),A)};z.prototype.GetCenterOfMass=function(){return w(jb(this.ud),B)};z.prototype.GetUserData=function(){return kb(this.ud)};
z.prototype.SetUserData=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);lb(c,b)};z.prototype.__destroy__=function(){mb(this.ud)};function C(){throw"cannot construct a VoidPtr, no constructor in IDL";}C.prototype=Object.create(r.prototype);C.prototype.constructor=C;C.prototype.xd=C;C.yd={};a.VoidPtr=C;C.prototype.__destroy__=function(){nb(this.ud)};function D(){throw"cannot construct a JPHString, no constructor in IDL";}D.prototype=Object.create(r.prototype);D.prototype.constructor=D;
D.prototype.xd=D;D.yd={};a.JPHString=D;D.prototype.c_str=function(){return wa(ob(this.ud))};D.prototype.__destroy__=function(){pb(this.ud)};function E(){throw"cannot construct a ArrayVec3, no constructor in IDL";}E.prototype=Object.create(r.prototype);E.prototype.constructor=E;E.prototype.xd=E;E.yd={};a.ArrayVec3=E;E.prototype.size=E.prototype.size=function(){return qb(this.ud)};E.prototype.at=E.prototype.at=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);return w(rb(c,b),B)};
E.prototype.push_back=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);sb(c,b)};E.prototype.__destroy__=function(){tb(this.ud)};function B(b,c,d){b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);d&&"object"===typeof d&&(d=d.ud);this.ud=void 0===b?ub():void 0===c?_emscripten_bind_Vec3_Vec3_1(b):void 0===d?_emscripten_bind_Vec3_Vec3_2(b,c):vb(b,c,d);v(B)[this.ud]=this}B.prototype=Object.create(r.prototype);B.prototype.constructor=B;B.prototype.xd=B;B.yd={};a.Vec3=B;
B.prototype.sZero=function(){return w(wb(this.ud),B)};B.prototype.Length=function(){return xb(this.ud)};B.prototype.GetX=function(){return yb(this.ud)};B.prototype.GetY=function(){return zb(this.ud)};B.prototype.GetZ=function(){return Ab(this.ud)};B.prototype.SetX=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Bb(c,b)};B.prototype.SetY=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Cb(c,b)};B.prototype.SetZ=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Db(c,b)};
B.prototype.__destroy__=function(){Eb(this.ud)};function G(b,c,d,g){b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);d&&"object"===typeof d&&(d=d.ud);g&&"object"===typeof g&&(g=g.ud);this.ud=void 0===b?Fb():void 0===c?_emscripten_bind_Quat_Quat_1(b):void 0===d?_emscripten_bind_Quat_Quat_2(b,c):void 0===g?_emscripten_bind_Quat_Quat_3(b,c,d):Gb(b,c,d,g);v(G)[this.ud]=this}G.prototype=Object.create(r.prototype);G.prototype.constructor=G;G.prototype.xd=G;G.yd={};a.Quat=G;
G.prototype.sIdentity=function(){return w(Hb(this.ud),G)};G.prototype.Length=function(){return Ib(this.ud)};G.prototype.GetX=function(){return Jb(this.ud)};G.prototype.GetY=function(){return Kb(this.ud)};G.prototype.GetZ=function(){return Lb(this.ud)};G.prototype.GetW=function(){return Mb(this.ud)};G.prototype.__destroy__=function(){Nb(this.ud)};
function H(b,c,d){b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);d&&"object"===typeof d&&(d=d.ud);this.ud=Ob(b,c,d);v(H)[this.ud]=this}H.prototype=Object.create(r.prototype);H.prototype.constructor=H;H.prototype.xd=H;H.yd={};a.Float3=H;H.prototype.get_x=H.prototype.ge=function(){return Pb(this.ud)};H.prototype.set_x=H.prototype.Ge=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Qb(c,b)};Object.defineProperty(H.prototype,"x",{get:H.prototype.ge,set:H.prototype.Ge});
H.prototype.get_y=H.prototype.he=function(){return Rb(this.ud)};H.prototype.set_y=H.prototype.He=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Sb(c,b)};Object.defineProperty(H.prototype,"y",{get:H.prototype.he,set:H.prototype.He});H.prototype.get_z=H.prototype.ie=function(){return Tb(this.ud)};H.prototype.set_z=H.prototype.Ie=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Ub(c,b)};Object.defineProperty(H.prototype,"z",{get:H.prototype.ie,set:H.prototype.Ie});
H.prototype.__destroy__=function(){Vb(this.ud)};function I(){throw"cannot construct a Mat44, no constructor in IDL";}I.prototype=Object.create(r.prototype);I.prototype.constructor=I;I.prototype.xd=I;I.yd={};a.Mat44=I;I.prototype.sRotationTranslation=function(b,c){var d=this.ud;b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);return w(Wb(d,b,c),I)};I.prototype.GetAxisX=function(){return w(Xb(this.ud),B)};I.prototype.GetAxisY=function(){return w(Yb(this.ud),B)};
I.prototype.GetAxisZ=function(){return w(Zb(this.ud),B)};I.prototype.GetQuaternion=function(){return w($b(this.ud),G)};I.prototype.GetTranslation=function(){return w(ac(this.ud),B)};I.prototype.__destroy__=function(){bc(this.ud)};function A(b,c){b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);this.ud=cc(b,c);v(A)[this.ud]=this}A.prototype=Object.create(r.prototype);A.prototype.constructor=A;A.prototype.xd=A;A.yd={};a.AABox=A;A.prototype.sBiggest=function(){return w(dc(this.ud),A)};
A.prototype.get_mMin=A.prototype.Zd=function(){return w(ec(this.ud),B)};A.prototype.set_mMin=A.prototype.ye=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);fc(c,b)};Object.defineProperty(A.prototype,"mMin",{get:A.prototype.Zd,set:A.prototype.ye});A.prototype.get_mMax=A.prototype.Ud=function(){return w(gc(this.ud),B)};A.prototype.set_mMax=A.prototype.te=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);hc(c,b)};Object.defineProperty(A.prototype,"mMax",{get:A.prototype.Ud,set:A.prototype.te});
A.prototype.__destroy__=function(){ic(this.ud)};function J(){throw"cannot construct a PhysicsMaterial, no constructor in IDL";}J.prototype=Object.create(r.prototype);J.prototype.constructor=J;J.prototype.xd=J;J.yd={};a.PhysicsMaterial=J;J.prototype.__destroy__=function(){jc(this.ud)};function K(){throw"cannot construct a GetTrianglesContext, no constructor in IDL";}K.prototype=Object.create(r.prototype);K.prototype.constructor=K;K.prototype.xd=K;K.yd={};a.GetTrianglesContext=K;
K.prototype.__destroy__=function(){kc(this.ud)};function y(){throw"cannot construct a ShapeResult, no constructor in IDL";}y.prototype=Object.create(r.prototype);y.prototype.constructor=y;y.prototype.xd=y;y.yd={};a.ShapeResult=y;y.prototype.IsValid=function(){return!!lc(this.ud)};y.prototype.HasError=function(){return!!mc(this.ud)};y.prototype.GetError=function(){return w(nc(this.ud),D)};y.prototype.Get=function(){return w(oc(this.ud),z)};y.prototype.__destroy__=function(){pc(this.ud)};
function L(b,c,d,g,h){b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);d&&"object"===typeof d&&(d=d.ud);g&&"object"===typeof g&&(g=g.ud);h&&"object"===typeof h&&(h=h.ud);this.ud=qc(b,c,d,g,h);v(L)[this.ud]=this}L.prototype=Object.create(r.prototype);L.prototype.constructor=L;L.prototype.xd=L;L.yd={};a.ShapeGetTriangles=L;L.prototype.GetNumTriangles=function(){return rc(this.ud)};
L.prototype.GetVertices=function(b,c,d,g){var h=this.ud;b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);d&&"object"===typeof d&&(d=d.ud);g&&"object"===typeof g&&(g=g.ud);sc(h,b,c,d,g)};L.prototype.GetMaterial=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);return w(tc(c,b),J)};L.prototype.__destroy__=function(){uc(this.ud)};function N(b,c){b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);this.ud=vc(b,c);v(N)[this.ud]=this}N.prototype=Object.create(z.prototype);
N.prototype.constructor=N;N.prototype.xd=N;N.yd={};a.SphereShape=N;N.prototype.GetType=function(){return wc(this.ud)};N.prototype.GetSubType=function(){return xc(this.ud)};N.prototype.MustBeStatic=function(){return!!yc(this.ud)};N.prototype.GetLocalBounds=function(){return w(zc(this.ud),A)};N.prototype.GetWorldSpaceBounds=function(b,c){var d=this.ud;b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);return w(Ac(d,b,c),A)};
N.prototype.GetCenterOfMass=function(){return w(Bc(this.ud),B)};N.prototype.GetUserData=function(){return Cc(this.ud)};N.prototype.SetUserData=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Dc(c,b)};N.prototype.__destroy__=function(){Ec(this.ud)};function O(b,c,d){b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);d&&"object"===typeof d&&(d=d.ud);this.ud=Fc(b,c,d);v(O)[this.ud]=this}O.prototype=Object.create(z.prototype);O.prototype.constructor=O;O.prototype.xd=O;O.yd={};
a.BoxShape=O;O.prototype.GetType=function(){return Gc(this.ud)};O.prototype.GetSubType=function(){return Hc(this.ud)};O.prototype.MustBeStatic=function(){return!!Ic(this.ud)};O.prototype.GetLocalBounds=function(){return w(Jc(this.ud),A)};O.prototype.GetWorldSpaceBounds=function(b,c){var d=this.ud;b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);return w(Kc(d,b,c),A)};O.prototype.GetCenterOfMass=function(){return w(Lc(this.ud),B)};O.prototype.GetUserData=function(){return Mc(this.ud)};
O.prototype.SetUserData=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Nc(c,b)};O.prototype.__destroy__=function(){Oc(this.ud)};function P(b,c,d,g){b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);d&&"object"===typeof d&&(d=d.ud);g&&"object"===typeof g&&(g=g.ud);this.ud=Pc(b,c,d,g);v(P)[this.ud]=this}P.prototype=Object.create(z.prototype);P.prototype.constructor=P;P.prototype.xd=P;P.yd={};a.CylinderShape=P;P.prototype.GetType=function(){return Qc(this.ud)};
P.prototype.GetSubType=function(){return Rc(this.ud)};P.prototype.MustBeStatic=function(){return!!Sc(this.ud)};P.prototype.GetLocalBounds=function(){return w(Tc(this.ud),A)};P.prototype.GetWorldSpaceBounds=function(b,c){var d=this.ud;b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);return w(Uc(d,b,c),A)};P.prototype.GetCenterOfMass=function(){return w(Vc(this.ud),B)};P.prototype.GetUserData=function(){return Wc(this.ud)};
P.prototype.SetUserData=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Xc(c,b)};P.prototype.__destroy__=function(){Yc(this.ud)};function Q(b,c,d){b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);d&&"object"===typeof d&&(d=d.ud);this.ud=Zc(b,c,d);v(Q)[this.ud]=this}Q.prototype=Object.create(z.prototype);Q.prototype.constructor=Q;Q.prototype.xd=Q;Q.yd={};a.CapsuleShape=Q;Q.prototype.GetType=function(){return $c(this.ud)};Q.prototype.GetSubType=function(){return ad(this.ud)};
Q.prototype.MustBeStatic=function(){return!!bd(this.ud)};Q.prototype.GetLocalBounds=function(){return w(cd(this.ud),A)};Q.prototype.GetWorldSpaceBounds=function(b,c){var d=this.ud;b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);return w(dd(d,b,c),A)};Q.prototype.GetCenterOfMass=function(){return w(ed(this.ud),B)};Q.prototype.GetUserData=function(){return fd(this.ud)};Q.prototype.SetUserData=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);gd(c,b)};
Q.prototype.__destroy__=function(){hd(this.ud)};function R(){this.ud=jd();v(R)[this.ud]=this}R.prototype=Object.create(x.prototype);R.prototype.constructor=R;R.prototype.xd=R;R.yd={};a.ConvexHullShapeSettings=R;R.prototype.Create=function(){return w(kd(this.ud),y)};R.prototype.get_mPoints=R.prototype.ce=function(){return w(ld(this.ud),E)};R.prototype.set_mPoints=R.prototype.Ce=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);md(c,b)};
Object.defineProperty(R.prototype,"mPoints",{get:R.prototype.ce,set:R.prototype.Ce});R.prototype.get_mMaxConvexRadius=R.prototype.Wd=function(){return nd(this.ud)};R.prototype.set_mMaxConvexRadius=R.prototype.ve=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);od(c,b)};Object.defineProperty(R.prototype,"mMaxConvexRadius",{get:R.prototype.Wd,set:R.prototype.ve});R.prototype.get_mMaxErrorConvexRadius=R.prototype.Xd=function(){return pd(this.ud)};
R.prototype.set_mMaxErrorConvexRadius=R.prototype.we=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);qd(c,b)};Object.defineProperty(R.prototype,"mMaxErrorConvexRadius",{get:R.prototype.Xd,set:R.prototype.we});R.prototype.get_mHullTolerance=R.prototype.Qd=function(){return rd(this.ud)};R.prototype.set_mHullTolerance=R.prototype.pe=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);sd(c,b)};Object.defineProperty(R.prototype,"mHullTolerance",{get:R.prototype.Qd,set:R.prototype.pe});
R.prototype.get_mUserData=R.prototype.Cd=function(){return td(this.ud)};R.prototype.set_mUserData=R.prototype.Dd=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);ud(c,b)};Object.defineProperty(R.prototype,"mUserData",{get:R.prototype.Cd,set:R.prototype.Dd});R.prototype.__destroy__=function(){vd(this.ud)};function S(){throw"cannot construct a ConvexHullShape, no constructor in IDL";}S.prototype=Object.create(z.prototype);S.prototype.constructor=S;S.prototype.xd=S;S.yd={};
a.ConvexHullShape=S;S.prototype.GetType=function(){return wd(this.ud)};S.prototype.GetSubType=function(){return xd(this.ud)};S.prototype.MustBeStatic=function(){return!!yd(this.ud)};S.prototype.GetLocalBounds=function(){return w(zd(this.ud),A)};S.prototype.GetWorldSpaceBounds=function(b,c){var d=this.ud;b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);return w(Ad(d,b,c),A)};S.prototype.GetCenterOfMass=function(){return w(Bd(this.ud),B)};S.prototype.GetUserData=function(){return Cd(this.ud)};
S.prototype.SetUserData=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Dd(c,b)};S.prototype.__destroy__=function(){Ed(this.ud)};function U(b){b&&"object"===typeof b&&(b=b.ud);this.ud=void 0===b?Fd():Gd(b);v(U)[this.ud]=this}U.prototype=Object.create(r.prototype);U.prototype.constructor=U;U.prototype.xd=U;U.yd={};a.BodyID=U;U.prototype.__destroy__=function(){Hd(this.ud)};function Body(){throw"cannot construct a Body, no constructor in IDL";}Body.prototype=Object.create(r.prototype);
Body.prototype.constructor=Body;Body.prototype.xd=Body;Body.yd={};a.Body=Body;Body.prototype.GetID=function(){return w(Id(this.ud),U)};Body.prototype.GetPosition=function(){return w(Jd(this.ud),B)};Body.prototype.GetRotation=function(){return w(Kd(this.ud),G)};Body.prototype.__destroy__=function(){Ld(this.ud)};function V(){throw"cannot construct a BodyInterface, no constructor in IDL";}V.prototype=Object.create(r.prototype);V.prototype.constructor=V;V.prototype.xd=V;V.yd={};a.BodyInterface=V;
V.prototype.CreateBody=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);return w(Md(c,b),Body)};V.prototype.AddBody=function(b,c){var d=this.ud;b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);Nd(d,b,c)};V.prototype.CreateAndAddBody=function(b,c){var d=this.ud;b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);return w(Od(d,b,c),U)};
V.prototype.GetPositionAndRotation=function(b,c,d){var g=this.ud;b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);d&&"object"===typeof d&&(d=d.ud);Pd(g,b,c,d)};V.prototype.__destroy__=function(){Qd(this.ud)};function W(){throw"cannot construct a PhysicsSystem, no constructor in IDL";}W.prototype=Object.create(r.prototype);W.prototype.constructor=W;W.prototype.xd=W;W.yd={};a.PhysicsSystem=W;W.prototype.GetBodyInterface=function(){return w(Rd(this.ud),V)};W.prototype.__destroy__=function(){Sd(this.ud)};
function X(b,c,d,g,h){b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);d&&"object"===typeof d&&(d=d.ud);g&&"object"===typeof g&&(g=g.ud);h&&"object"===typeof h&&(h=h.ud);this.ud=Td(b,c,d,g,h);v(X)[this.ud]=this}X.prototype=Object.create(r.prototype);X.prototype.constructor=X;X.prototype.xd=X;X.yd={};a.BodyCreationSettings=X;X.prototype.get_mPosition=X.prototype.de=function(){return w(Ud(this.ud),B)};
X.prototype.set_mPosition=X.prototype.De=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Vd(c,b)};Object.defineProperty(X.prototype,"mPosition",{get:X.prototype.de,set:X.prototype.De});X.prototype.get_mRotation=X.prototype.fe=function(){return w(Wd(this.ud),G)};X.prototype.set_mRotation=X.prototype.Fe=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Xd(c,b)};Object.defineProperty(X.prototype,"mRotation",{get:X.prototype.fe,set:X.prototype.Fe});
X.prototype.get_mLinearVelocity=X.prototype.Td=function(){return w(Yd(this.ud),B)};X.prototype.set_mLinearVelocity=X.prototype.se=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Zd(c,b)};Object.defineProperty(X.prototype,"mLinearVelocity",{get:X.prototype.Td,set:X.prototype.se});X.prototype.get_mAngularVelocity=X.prototype.Nd=function(){return w($d(this.ud),B)};X.prototype.set_mAngularVelocity=X.prototype.me=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);ae(c,b)};
Object.defineProperty(X.prototype,"mAngularVelocity",{get:X.prototype.Nd,set:X.prototype.me});X.prototype.get_mUserData=X.prototype.Cd=function(){return be(this.ud)};X.prototype.set_mUserData=X.prototype.Dd=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);ce(c,b)};Object.defineProperty(X.prototype,"mUserData",{get:X.prototype.Cd,set:X.prototype.Dd});X.prototype.get_mObjectLayer=X.prototype.be=function(){return de(this.ud)};
X.prototype.set_mObjectLayer=X.prototype.Be=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);ee(c,b)};Object.defineProperty(X.prototype,"mObjectLayer",{get:X.prototype.be,set:X.prototype.Be});X.prototype.get_mMotionType=X.prototype.ae=function(){return fe(this.ud)};X.prototype.set_mMotionType=X.prototype.Ae=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);ge(c,b)};Object.defineProperty(X.prototype,"mMotionType",{get:X.prototype.ae,set:X.prototype.Ae});
X.prototype.get_mAllowDynamicOrKinematic=X.prototype.Kd=function(){return!!he(this.ud)};X.prototype.set_mAllowDynamicOrKinematic=X.prototype.je=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);ie(c,b)};Object.defineProperty(X.prototype,"mAllowDynamicOrKinematic",{get:X.prototype.Kd,set:X.prototype.je});X.prototype.get_mIsSensor=X.prototype.Rd=function(){return!!je(this.ud)};X.prototype.set_mIsSensor=X.prototype.qe=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);ke(c,b)};
Object.defineProperty(X.prototype,"mIsSensor",{get:X.prototype.Rd,set:X.prototype.qe});X.prototype.get_mMotionQuality=X.prototype.$d=function(){return le(this.ud)};X.prototype.set_mMotionQuality=X.prototype.ze=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);me(c,b)};Object.defineProperty(X.prototype,"mMotionQuality",{get:X.prototype.$d,set:X.prototype.ze});X.prototype.get_mAllowSleeping=X.prototype.Ld=function(){return!!ne(this.ud)};
X.prototype.set_mAllowSleeping=X.prototype.ke=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);oe(c,b)};Object.defineProperty(X.prototype,"mAllowSleeping",{get:X.prototype.Ld,set:X.prototype.ke});X.prototype.get_mFriction=X.prototype.Od=function(){return pe(this.ud)};X.prototype.set_mFriction=X.prototype.ne=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);qe(c,b)};Object.defineProperty(X.prototype,"mFriction",{get:X.prototype.Od,set:X.prototype.ne});
X.prototype.get_mRestitution=X.prototype.ee=function(){return re(this.ud)};X.prototype.set_mRestitution=X.prototype.Ee=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);se(c,b)};Object.defineProperty(X.prototype,"mRestitution",{get:X.prototype.ee,set:X.prototype.Ee});X.prototype.get_mLinearDamping=X.prototype.Sd=function(){return te(this.ud)};X.prototype.set_mLinearDamping=X.prototype.re=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);ue(c,b)};
Object.defineProperty(X.prototype,"mLinearDamping",{get:X.prototype.Sd,set:X.prototype.re});X.prototype.get_mAngularDamping=X.prototype.Md=function(){return ve(this.ud)};X.prototype.set_mAngularDamping=X.prototype.le=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);we(c,b)};Object.defineProperty(X.prototype,"mAngularDamping",{get:X.prototype.Md,set:X.prototype.le});X.prototype.get_mMaxLinearVelocity=X.prototype.Yd=function(){return xe(this.ud)};
X.prototype.set_mMaxLinearVelocity=X.prototype.xe=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);ye(c,b)};Object.defineProperty(X.prototype,"mMaxLinearVelocity",{get:X.prototype.Yd,set:X.prototype.xe});X.prototype.get_mMaxAngularVelocity=X.prototype.Vd=function(){return ze(this.ud)};X.prototype.set_mMaxAngularVelocity=X.prototype.ue=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Ae(c,b)};Object.defineProperty(X.prototype,"mMaxAngularVelocity",{get:X.prototype.Vd,set:X.prototype.ue});
X.prototype.get_mGravityFactor=X.prototype.Pd=function(){return Be(this.ud)};X.prototype.set_mGravityFactor=X.prototype.oe=function(b){var c=this.ud;b&&"object"===typeof b&&(b=b.ud);Ce(c,b)};Object.defineProperty(X.prototype,"mGravityFactor",{get:X.prototype.Pd,set:X.prototype.oe});X.prototype.__destroy__=function(){De(this.ud)};function Z(){this.ud=Ee();v(Z)[this.ud]=this}Z.prototype=Object.create(r.prototype);Z.prototype.constructor=Z;Z.prototype.xd=Z;Z.yd={};a.JoltInterface=Z;
Z.prototype.Step=function(b,c,d){var g=this.ud;b&&"object"===typeof b&&(b=b.ud);c&&"object"===typeof c&&(c=c.ud);d&&"object"===typeof d&&(d=d.ud);Fe(g,b,c,d)};Z.prototype.GetPhysicsSystem=function(){return w(Ge(this.ud),W)};Z.prototype.__destroy__=function(){He(this.ud)};
(function(){function b(){a.MOVING=Ie();a.NON_MOVING=Je();a.Static=Ke();a.Kinematic=Le();a.Dynamic=Me();a.Discrete=Ne();a.LinearCast=Oe();a.Activate=Pe();a.DontActivate=Qe();a.Convex=Re();a.Compound=Se();a.Decorated=Te();a.Mesh=Ue();a.HeightField=Ve();a.Sphere=We();a.Box=Xe();a.Triangle=Ye();a.Capsule=Ze();a.TaperedCapsule=$e();a.Cylinder=af();a.ConvexHull=bf();a.StaticCompound=cf();a.MutableCompound=df();a.RotatedTranslated=ef();a.Scaled=ff();a.OffsetCenterOfMass=gf();a.Mesh=hf();a.HeightField=jf()}
Ca?b():Aa.unshift(b)})();this.Jolt=a;


  return Jolt.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Jolt;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Jolt; });
else if (typeof exports === 'object')
  exports["Jolt"] = Jolt;
