// This is JoltPhysics.js, a web assembly version of JoltPhysics

var Jolt = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Jolt) {
  Jolt = Jolt || {};


var a;a||(a=typeof Jolt !== 'undefined' ? Jolt : {});var aa,ba;a.ready=new Promise(function(b,c){aa=b;ba=c});var ca=Object.assign({},a),da="./this.program",ea="object"==typeof window,d="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,n="",ha,p,q,fs,t,ia;
if(fa)n=d?require("path").dirname(n)+"/":__dirname+"/",ia=()=>{t||(fs=require("fs"),t=require("path"))},ha=function(b,c){ia();b=t.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")},q=b=>{b=ha(b,!0);b.buffer||(b=new Uint8Array(b));return b},p=(b,c,e)=>{ia();b=t.normalize(b);fs.readFile(b,function(g,h){g?e(g):c(h.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",function(b){throw b;
}),a.inspect=function(){return"[Emscripten Module object]"};else if(ea||d)d?n=self.location.href:"undefined"!=typeof document&&document.currentScript&&(n=document.currentScript.src),_scriptDir&&(n=_scriptDir),0!==n.indexOf("blob:")?n=n.substr(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1):n="",ha=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},d&&(q=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),
p=(b,c,e)=>{var g=new XMLHttpRequest;g.open("GET",b,!0);g.responseType="arraybuffer";g.onload=()=>{200==g.status||0==g.status&&g.response?c(g.response):e()};g.onerror=e;g.send(null)};var ja=a.print||console.log.bind(console),u=a.printErr||console.warn.bind(console);Object.assign(a,ca);ca=null;a.thisProgram&&(da=a.thisProgram);var w;a.wasmBinary&&(w=a.wasmBinary);var noExitRuntime=a.noExitRuntime||!0;"object"!=typeof WebAssembly&&x("no native wasm support detected");
var ka,la=!1,ma="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(b,c){for(var e=c+NaN,g=c;b[g]&&!(g>=e);)++g;if(16<g-c&&b.buffer&&ma)return ma.decode(b.subarray(c,g));for(e="";c<g;){var h=b[c++];if(h&128){var k=b[c++]&63;if(192==(h&224))e+=String.fromCharCode((h&31)<<6|k);else{var F=b[c++]&63;h=224==(h&240)?(h&15)<<12|k<<6|F:(h&7)<<18|k<<12|F<<6|b[c++]&63;65536>h?e+=String.fromCharCode(h):(h-=65536,e+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else e+=String.fromCharCode(h)}return e}var y,z,A,B,oa=[],pa=[],qa=[],ra=!1;
function sa(){var b=a.preRun.shift();oa.unshift(b)}var C=0,ta=null,D=null;function x(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";u(b);la=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ba(b);throw b;}function ua(){return E.startsWith("data:application/octet-stream;base64,")}var E;E="jolt.wasm.wasm";if(!ua()){var va=E;E=a.locateFile?a.locateFile(va,n):n+va}
function wa(){var b=E;try{if(b==E&&w)return new Uint8Array(w);if(q)return q(b);throw"both async and sync fetching of the wasm failed";}catch(c){x(c)}}
function xa(){if(!w&&(ea||d)){if("function"==typeof fetch&&!E.startsWith("file://"))return fetch(E,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+E+"'";return b.arrayBuffer()}).catch(function(){return wa()});if(p)return new Promise(function(b,c){p(E,function(e){b(new Uint8Array(e))},c)})}return Promise.resolve().then(function(){return wa()})}function ya(b){for(;0<b.length;)b.shift()(a)}
function za(b){this.ab=b-24;this.Kb=function(c){B[this.ab+4>>2]=c};this.pb=function(c){B[this.ab+8>>2]=c};this.Ib=function(){A[this.ab>>2]=0};this.ob=function(){y[this.ab+12>>0]=0};this.Jb=function(){y[this.ab+13>>0]=0};this.mb=function(c,e){this.nb();this.Kb(c);this.pb(e);this.Ib();this.ob();this.Jb()};this.nb=function(){B[this.ab+16>>2]=0}}var Aa=0,Ba={};
function Fa(){if(!Ga){var b={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},c;for(c in Ba)void 0===Ba[c]?delete b[c]:b[c]=Ba[c];var e=[];for(c in b)e.push(c+"="+b[c]);Ga=e}return Ga}var Ga,Ha=[null,[],[]];function G(b){return 0===b%4&&(0!==b%100||0===b%400)}
var Ia=[31,29,31,30,31,30,31,31,30,31,30,31],Ja=[31,28,31,30,31,30,31,31,30,31,30,31];
function Ka(b){for(var c=0,e=0;e<b.length;++e){var g=b.charCodeAt(e);127>=g?c++:2047>=g?c+=2:55296<=g&&57343>=g?(c+=4,++e):c+=3}c=Array(c+1);g=c.length;e=0;if(0<g){g=e+g-1;for(var h=0;h<b.length;++h){var k=b.charCodeAt(h);if(55296<=k&&57343>=k){var F=b.charCodeAt(++h);k=65536+((k&1023)<<10)|F&1023}if(127>=k){if(e>=g)break;c[e++]=k}else{if(2047>=k){if(e+1>=g)break;c[e++]=192|k>>6}else{if(65535>=k){if(e+2>=g)break;c[e++]=224|k>>12}else{if(e+3>=g)break;c[e++]=240|k>>18;c[e++]=128|k>>12&63}c[e++]=128|
k>>6&63}c[e++]=128|k&63}}c[e]=0}return c}
function La(b,c,e,g){function h(f,l,m){for(f="number"==typeof f?f.toString():f||"";f.length<l;)f=m[0]+f;return f}function k(f,l){return h(f,l,"0")}function F(f,l){function m(Ca){return 0>Ca?-1:0<Ca?1:0}var M;0===(M=m(f.getFullYear()-l.getFullYear()))&&0===(M=m(f.getMonth()-l.getMonth()))&&(M=m(f.getDate()-l.getDate()));return M}function V(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function Q(f){var l=f.hb;for(f=new Date((new Date(f.ib+1900,0,1)).getTime());0<l;){var m=f.getMonth(),M=(G(f.getFullYear())?Ia:Ja)[m];if(l>M-f.getDate())l-=M-f.getDate()+1,f.setDate(1),11>m?f.setMonth(m+1):(f.setMonth(0),f.setFullYear(f.getFullYear()+1));else{f.setDate(f.getDate()+l);break}}m=new Date(f.getFullYear()+1,0,4);l=V(new Date(f.getFullYear(),
0,4));m=V(m);return 0>=F(l,f)?0>=F(m,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var v=A[g+40>>2];g={ec:A[g>>2],dc:A[g+4>>2],jb:A[g+8>>2],lb:A[g+12>>2],kb:A[g+16>>2],ib:A[g+20>>2],gb:A[g+24>>2],hb:A[g+28>>2],hc:A[g+32>>2],cc:A[g+36>>2],fc:v?v?na(z,v):"":""};e=e?na(z,e):"";v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in v)e=e.replace(new RegExp(r,"g"),v[r]);var Da="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Ea="January February March April May June July August September October November December".split(" ");v={"%a":function(f){return Da[f.gb].substring(0,3)},"%A":function(f){return Da[f.gb]},"%b":function(f){return Ea[f.kb].substring(0,
3)},"%B":function(f){return Ea[f.kb]},"%C":function(f){return k((f.ib+1900)/100|0,2)},"%d":function(f){return k(f.lb,2)},"%e":function(f){return h(f.lb,2," ")},"%g":function(f){return Q(f).toString().substring(2)},"%G":function(f){return Q(f)},"%H":function(f){return k(f.jb,2)},"%I":function(f){f=f.jb;0==f?f=12:12<f&&(f-=12);return k(f,2)},"%j":function(f){for(var l=0,m=0;m<=f.kb-1;l+=(G(f.ib+1900)?Ia:Ja)[m++]);return k(f.lb+l,3)},"%m":function(f){return k(f.kb+1,2)},"%M":function(f){return k(f.dc,
2)},"%n":function(){return"\n"},"%p":function(f){return 0<=f.jb&&12>f.jb?"AM":"PM"},"%S":function(f){return k(f.ec,2)},"%t":function(){return"\t"},"%u":function(f){return f.gb||7},"%U":function(f){return k(Math.floor((f.hb+7-f.gb)/7),2)},"%V":function(f){var l=Math.floor((f.hb+7-(f.gb+6)%7)/7);2>=(f.gb+371-f.hb-2)%7&&l++;if(l)53==l&&(m=(f.gb+371-f.hb)%7,4==m||3==m&&G(f.ib)||(l=1));else{l=52;var m=(f.gb+7-f.hb-1)%7;(4==m||5==m&&G(f.ib%400-1))&&l++}return k(l,2)},"%w":function(f){return f.gb},"%W":function(f){return k(Math.floor((f.hb+
7-(f.gb+6)%7)/7),2)},"%y":function(f){return(f.ib+1900).toString().substring(2)},"%Y":function(f){return f.ib+1900},"%z":function(f){f=f.cc;var l=0<=f;f=Math.abs(f)/60;return(l?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.fc},"%%":function(){return"%"}};e=e.replace(/%%/g,"\x00\x00");for(r in v)e.includes(r)&&(e=e.replace(new RegExp(r,"g"),v[r](g)));e=e.replace(/\0\0/g,"%");r=Ka(e);if(r.length>c)return 0;y.set(r,b);return r.length-1}
var Na={b:function(b){return Ma(b+24)+24},a:function(b,c,e){(new za(b)).mb(c,e);Aa++;throw b;},d:function(){x("")},l:function(){return z.length},e:fa?()=>{var b=process.hrtime();return 1E3*b[0]+b[1]/1E6}:()=>performance.now(),j:function(b,c,e){z.copyWithin(b,c,c+e)},i:function(){x("OOM")},n:function(b,c){var e=0;Fa().forEach(function(g,h){var k=c+e;h=B[b+4*h>>2]=k;for(k=0;k<g.length;++k)y[h++>>0]=g.charCodeAt(k);y[h>>0]=0;e+=g.length+1});return 0},f:function(b,c){var e=Fa();B[b>>2]=e.length;var g=
0;e.forEach(function(h){g+=h.length+1});B[c>>2]=g;return 0},g:function(){return 52},h:function(){return 52},k:function(){return 70},c:function(b,c,e,g){for(var h=0,k=0;k<e;k++){var F=B[c>>2],V=B[c+4>>2];c+=8;for(var Q=0;Q<V;Q++){var v=z[F+Q],r=Ha[b];0===v||10===v?((1===b?ja:u)(na(r,0)),r.length=0):r.push(v)}h+=V}B[g>>2]=h;return 0},m:function(b,c,e,g){return La(b,c,e,g)}};
(function(){function b(h){a.asm=h.exports;ka=a.asm.o;h=ka.buffer;a.HEAP8=y=new Int8Array(h);a.HEAP16=new Int16Array(h);a.HEAP32=A=new Int32Array(h);a.HEAPU8=z=new Uint8Array(h);a.HEAPU16=new Uint16Array(h);a.HEAPU32=B=new Uint32Array(h);a.HEAPF32=new Float32Array(h);a.HEAPF64=new Float64Array(h);pa.unshift(a.asm.p);C--;a.monitorRunDependencies&&a.monitorRunDependencies(C);0==C&&(null!==ta&&(clearInterval(ta),ta=null),D&&(h=D,D=null,h()))}function c(h){b(h.instance)}function e(h){return xa().then(function(k){return WebAssembly.instantiate(k,
g)}).then(function(k){return k}).then(h,function(k){u("failed to asynchronously prepare wasm: "+k);x(k)})}var g={a:Na};C++;a.monitorRunDependencies&&a.monitorRunDependencies(C);if(a.instantiateWasm)try{return a.instantiateWasm(g,b)}catch(h){return u("Module.instantiateWasm callback failed with error: "+h),!1}(function(){return w||"function"!=typeof WebAssembly.instantiateStreaming||ua()||E.startsWith("file://")||fa||"function"!=typeof fetch?e(c):fetch(E,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,
g).then(c,function(k){u("wasm streaming compile failed: "+k);u("falling back to ArrayBuffer instantiation");return e(c)})})})().catch(ba);return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.p).apply(null,arguments)};
var Oa=a._emscripten_bind_Shape___destroy___0=function(){return(Oa=a._emscripten_bind_Shape___destroy___0=a.asm.q).apply(null,arguments)},Pa=a._emscripten_bind_VoidPtr___destroy___0=function(){return(Pa=a._emscripten_bind_VoidPtr___destroy___0=a.asm.r).apply(null,arguments)},Qa=a._emscripten_bind_Vec3_Vec3_0=function(){return(Qa=a._emscripten_bind_Vec3_Vec3_0=a.asm.s).apply(null,arguments)},Ra=a._emscripten_bind_Vec3_Vec3_3=function(){return(Ra=a._emscripten_bind_Vec3_Vec3_3=a.asm.t).apply(null,arguments)},
Sa=a._emscripten_bind_Vec3_Length_0=function(){return(Sa=a._emscripten_bind_Vec3_Length_0=a.asm.u).apply(null,arguments)},Ta=a._emscripten_bind_Vec3_GetX_0=function(){return(Ta=a._emscripten_bind_Vec3_GetX_0=a.asm.v).apply(null,arguments)},Ua=a._emscripten_bind_Vec3_GetY_0=function(){return(Ua=a._emscripten_bind_Vec3_GetY_0=a.asm.w).apply(null,arguments)},Va=a._emscripten_bind_Vec3_GetZ_0=function(){return(Va=a._emscripten_bind_Vec3_GetZ_0=a.asm.x).apply(null,arguments)},Wa=a._emscripten_bind_Vec3_SetX_1=
function(){return(Wa=a._emscripten_bind_Vec3_SetX_1=a.asm.y).apply(null,arguments)},Xa=a._emscripten_bind_Vec3_SetY_1=function(){return(Xa=a._emscripten_bind_Vec3_SetY_1=a.asm.z).apply(null,arguments)},Ya=a._emscripten_bind_Vec3_SetZ_1=function(){return(Ya=a._emscripten_bind_Vec3_SetZ_1=a.asm.A).apply(null,arguments)},Za=a._emscripten_bind_Vec3___destroy___0=function(){return(Za=a._emscripten_bind_Vec3___destroy___0=a.asm.B).apply(null,arguments)},$a=a._emscripten_bind_Quat_Quat_0=function(){return($a=
a._emscripten_bind_Quat_Quat_0=a.asm.C).apply(null,arguments)},ab=a._emscripten_bind_Quat_Quat_4=function(){return(ab=a._emscripten_bind_Quat_Quat_4=a.asm.D).apply(null,arguments)},bb=a._emscripten_bind_Quat_Length_0=function(){return(bb=a._emscripten_bind_Quat_Length_0=a.asm.E).apply(null,arguments)},cb=a._emscripten_bind_Quat_GetX_0=function(){return(cb=a._emscripten_bind_Quat_GetX_0=a.asm.F).apply(null,arguments)},db=a._emscripten_bind_Quat_GetY_0=function(){return(db=a._emscripten_bind_Quat_GetY_0=
a.asm.G).apply(null,arguments)},eb=a._emscripten_bind_Quat_GetZ_0=function(){return(eb=a._emscripten_bind_Quat_GetZ_0=a.asm.H).apply(null,arguments)},fb=a._emscripten_bind_Quat_GetW_0=function(){return(fb=a._emscripten_bind_Quat_GetW_0=a.asm.I).apply(null,arguments)},gb=a._emscripten_bind_Quat___destroy___0=function(){return(gb=a._emscripten_bind_Quat___destroy___0=a.asm.J).apply(null,arguments)},hb=a._emscripten_bind_PhysicsMaterial___destroy___0=function(){return(hb=a._emscripten_bind_PhysicsMaterial___destroy___0=
a.asm.K).apply(null,arguments)},ib=a._emscripten_bind_SphereShape_SphereShape_2=function(){return(ib=a._emscripten_bind_SphereShape_SphereShape_2=a.asm.L).apply(null,arguments)},jb=a._emscripten_bind_SphereShape___destroy___0=function(){return(jb=a._emscripten_bind_SphereShape___destroy___0=a.asm.M).apply(null,arguments)},kb=a._emscripten_bind_BoxShape_BoxShape_3=function(){return(kb=a._emscripten_bind_BoxShape_BoxShape_3=a.asm.N).apply(null,arguments)},lb=a._emscripten_bind_BoxShape___destroy___0=
function(){return(lb=a._emscripten_bind_BoxShape___destroy___0=a.asm.O).apply(null,arguments)},mb=a._emscripten_bind_CylinderShape_CylinderShape_4=function(){return(mb=a._emscripten_bind_CylinderShape_CylinderShape_4=a.asm.P).apply(null,arguments)},nb=a._emscripten_bind_CylinderShape___destroy___0=function(){return(nb=a._emscripten_bind_CylinderShape___destroy___0=a.asm.Q).apply(null,arguments)},ob=a._emscripten_bind_BodyID_BodyID_0=function(){return(ob=a._emscripten_bind_BodyID_BodyID_0=a.asm.R).apply(null,
arguments)},pb=a._emscripten_bind_BodyID_BodyID_1=function(){return(pb=a._emscripten_bind_BodyID_BodyID_1=a.asm.S).apply(null,arguments)},qb=a._emscripten_bind_BodyID___destroy___0=function(){return(qb=a._emscripten_bind_BodyID___destroy___0=a.asm.T).apply(null,arguments)},rb=a._emscripten_bind_Body_GetID_0=function(){return(rb=a._emscripten_bind_Body_GetID_0=a.asm.U).apply(null,arguments)},sb=a._emscripten_bind_Body_GetPosition_0=function(){return(sb=a._emscripten_bind_Body_GetPosition_0=a.asm.V).apply(null,
arguments)},tb=a._emscripten_bind_Body_GetRotation_0=function(){return(tb=a._emscripten_bind_Body_GetRotation_0=a.asm.W).apply(null,arguments)},ub=a._emscripten_bind_Body___destroy___0=function(){return(ub=a._emscripten_bind_Body___destroy___0=a.asm.X).apply(null,arguments)},vb=a._emscripten_bind_BodyInterface_CreateBody_1=function(){return(vb=a._emscripten_bind_BodyInterface_CreateBody_1=a.asm.Y).apply(null,arguments)},wb=a._emscripten_bind_BodyInterface_AddBody_2=function(){return(wb=a._emscripten_bind_BodyInterface_AddBody_2=
a.asm.Z).apply(null,arguments)},xb=a._emscripten_bind_BodyInterface_CreateAndAddBody_2=function(){return(xb=a._emscripten_bind_BodyInterface_CreateAndAddBody_2=a.asm._).apply(null,arguments)},yb=a._emscripten_bind_BodyInterface_GetPositionAndRotation_3=function(){return(yb=a._emscripten_bind_BodyInterface_GetPositionAndRotation_3=a.asm.$).apply(null,arguments)},zb=a._emscripten_bind_BodyInterface___destroy___0=function(){return(zb=a._emscripten_bind_BodyInterface___destroy___0=a.asm.aa).apply(null,
arguments)},Ab=a._emscripten_bind_PhysicsSystem_GetBodyInterface_0=function(){return(Ab=a._emscripten_bind_PhysicsSystem_GetBodyInterface_0=a.asm.ba).apply(null,arguments)},Bb=a._emscripten_bind_PhysicsSystem___destroy___0=function(){return(Bb=a._emscripten_bind_PhysicsSystem___destroy___0=a.asm.ca).apply(null,arguments)},Cb=a._emscripten_bind_BodyCreationSettings_BodyCreationSettings_5=function(){return(Cb=a._emscripten_bind_BodyCreationSettings_BodyCreationSettings_5=a.asm.da).apply(null,arguments)},
Db=a._emscripten_bind_BodyCreationSettings_get_mPosition_0=function(){return(Db=a._emscripten_bind_BodyCreationSettings_get_mPosition_0=a.asm.ea).apply(null,arguments)},Eb=a._emscripten_bind_BodyCreationSettings_set_mPosition_1=function(){return(Eb=a._emscripten_bind_BodyCreationSettings_set_mPosition_1=a.asm.fa).apply(null,arguments)},Fb=a._emscripten_bind_BodyCreationSettings_get_mRotation_0=function(){return(Fb=a._emscripten_bind_BodyCreationSettings_get_mRotation_0=a.asm.ga).apply(null,arguments)},
Gb=a._emscripten_bind_BodyCreationSettings_set_mRotation_1=function(){return(Gb=a._emscripten_bind_BodyCreationSettings_set_mRotation_1=a.asm.ha).apply(null,arguments)},Hb=a._emscripten_bind_BodyCreationSettings_get_mLinearVelocity_0=function(){return(Hb=a._emscripten_bind_BodyCreationSettings_get_mLinearVelocity_0=a.asm.ia).apply(null,arguments)},Ib=a._emscripten_bind_BodyCreationSettings_set_mLinearVelocity_1=function(){return(Ib=a._emscripten_bind_BodyCreationSettings_set_mLinearVelocity_1=a.asm.ja).apply(null,
arguments)},Jb=a._emscripten_bind_BodyCreationSettings_get_mAngularVelocity_0=function(){return(Jb=a._emscripten_bind_BodyCreationSettings_get_mAngularVelocity_0=a.asm.ka).apply(null,arguments)},Kb=a._emscripten_bind_BodyCreationSettings_set_mAngularVelocity_1=function(){return(Kb=a._emscripten_bind_BodyCreationSettings_set_mAngularVelocity_1=a.asm.la).apply(null,arguments)},Lb=a._emscripten_bind_BodyCreationSettings_get_mUserData_0=function(){return(Lb=a._emscripten_bind_BodyCreationSettings_get_mUserData_0=
a.asm.ma).apply(null,arguments)},Mb=a._emscripten_bind_BodyCreationSettings_set_mUserData_1=function(){return(Mb=a._emscripten_bind_BodyCreationSettings_set_mUserData_1=a.asm.na).apply(null,arguments)},Nb=a._emscripten_bind_BodyCreationSettings_get_mObjectLayer_0=function(){return(Nb=a._emscripten_bind_BodyCreationSettings_get_mObjectLayer_0=a.asm.oa).apply(null,arguments)},Ob=a._emscripten_bind_BodyCreationSettings_set_mObjectLayer_1=function(){return(Ob=a._emscripten_bind_BodyCreationSettings_set_mObjectLayer_1=
a.asm.pa).apply(null,arguments)},Pb=a._emscripten_bind_BodyCreationSettings_get_mMotionType_0=function(){return(Pb=a._emscripten_bind_BodyCreationSettings_get_mMotionType_0=a.asm.qa).apply(null,arguments)},Qb=a._emscripten_bind_BodyCreationSettings_set_mMotionType_1=function(){return(Qb=a._emscripten_bind_BodyCreationSettings_set_mMotionType_1=a.asm.ra).apply(null,arguments)},Rb=a._emscripten_bind_BodyCreationSettings_get_mAllowDynamicOrKinematic_0=function(){return(Rb=a._emscripten_bind_BodyCreationSettings_get_mAllowDynamicOrKinematic_0=
a.asm.sa).apply(null,arguments)},Sb=a._emscripten_bind_BodyCreationSettings_set_mAllowDynamicOrKinematic_1=function(){return(Sb=a._emscripten_bind_BodyCreationSettings_set_mAllowDynamicOrKinematic_1=a.asm.ta).apply(null,arguments)},Tb=a._emscripten_bind_BodyCreationSettings_get_mIsSensor_0=function(){return(Tb=a._emscripten_bind_BodyCreationSettings_get_mIsSensor_0=a.asm.ua).apply(null,arguments)},Ub=a._emscripten_bind_BodyCreationSettings_set_mIsSensor_1=function(){return(Ub=a._emscripten_bind_BodyCreationSettings_set_mIsSensor_1=
a.asm.va).apply(null,arguments)},Vb=a._emscripten_bind_BodyCreationSettings_get_mMotionQuality_0=function(){return(Vb=a._emscripten_bind_BodyCreationSettings_get_mMotionQuality_0=a.asm.wa).apply(null,arguments)},Wb=a._emscripten_bind_BodyCreationSettings_set_mMotionQuality_1=function(){return(Wb=a._emscripten_bind_BodyCreationSettings_set_mMotionQuality_1=a.asm.xa).apply(null,arguments)},Xb=a._emscripten_bind_BodyCreationSettings_get_mAllowSleeping_0=function(){return(Xb=a._emscripten_bind_BodyCreationSettings_get_mAllowSleeping_0=
a.asm.ya).apply(null,arguments)},Yb=a._emscripten_bind_BodyCreationSettings_set_mAllowSleeping_1=function(){return(Yb=a._emscripten_bind_BodyCreationSettings_set_mAllowSleeping_1=a.asm.za).apply(null,arguments)},Zb=a._emscripten_bind_BodyCreationSettings_get_mFriction_0=function(){return(Zb=a._emscripten_bind_BodyCreationSettings_get_mFriction_0=a.asm.Aa).apply(null,arguments)},$b=a._emscripten_bind_BodyCreationSettings_set_mFriction_1=function(){return($b=a._emscripten_bind_BodyCreationSettings_set_mFriction_1=
a.asm.Ba).apply(null,arguments)},ac=a._emscripten_bind_BodyCreationSettings_get_mRestitution_0=function(){return(ac=a._emscripten_bind_BodyCreationSettings_get_mRestitution_0=a.asm.Ca).apply(null,arguments)},bc=a._emscripten_bind_BodyCreationSettings_set_mRestitution_1=function(){return(bc=a._emscripten_bind_BodyCreationSettings_set_mRestitution_1=a.asm.Da).apply(null,arguments)},cc=a._emscripten_bind_BodyCreationSettings_get_mLinearDamping_0=function(){return(cc=a._emscripten_bind_BodyCreationSettings_get_mLinearDamping_0=
a.asm.Ea).apply(null,arguments)},dc=a._emscripten_bind_BodyCreationSettings_set_mLinearDamping_1=function(){return(dc=a._emscripten_bind_BodyCreationSettings_set_mLinearDamping_1=a.asm.Fa).apply(null,arguments)},ec=a._emscripten_bind_BodyCreationSettings_get_mAngularDamping_0=function(){return(ec=a._emscripten_bind_BodyCreationSettings_get_mAngularDamping_0=a.asm.Ga).apply(null,arguments)},fc=a._emscripten_bind_BodyCreationSettings_set_mAngularDamping_1=function(){return(fc=a._emscripten_bind_BodyCreationSettings_set_mAngularDamping_1=
a.asm.Ha).apply(null,arguments)},gc=a._emscripten_bind_BodyCreationSettings_get_mMaxLinearVelocity_0=function(){return(gc=a._emscripten_bind_BodyCreationSettings_get_mMaxLinearVelocity_0=a.asm.Ia).apply(null,arguments)},hc=a._emscripten_bind_BodyCreationSettings_set_mMaxLinearVelocity_1=function(){return(hc=a._emscripten_bind_BodyCreationSettings_set_mMaxLinearVelocity_1=a.asm.Ja).apply(null,arguments)},ic=a._emscripten_bind_BodyCreationSettings_get_mMaxAngularVelocity_0=function(){return(ic=a._emscripten_bind_BodyCreationSettings_get_mMaxAngularVelocity_0=
a.asm.Ka).apply(null,arguments)},jc=a._emscripten_bind_BodyCreationSettings_set_mMaxAngularVelocity_1=function(){return(jc=a._emscripten_bind_BodyCreationSettings_set_mMaxAngularVelocity_1=a.asm.La).apply(null,arguments)},kc=a._emscripten_bind_BodyCreationSettings_get_mGravityFactor_0=function(){return(kc=a._emscripten_bind_BodyCreationSettings_get_mGravityFactor_0=a.asm.Ma).apply(null,arguments)},lc=a._emscripten_bind_BodyCreationSettings_set_mGravityFactor_1=function(){return(lc=a._emscripten_bind_BodyCreationSettings_set_mGravityFactor_1=
a.asm.Na).apply(null,arguments)},mc=a._emscripten_bind_BodyCreationSettings___destroy___0=function(){return(mc=a._emscripten_bind_BodyCreationSettings___destroy___0=a.asm.Oa).apply(null,arguments)},nc=a._emscripten_bind_JoltInterface_JoltInterface_0=function(){return(nc=a._emscripten_bind_JoltInterface_JoltInterface_0=a.asm.Pa).apply(null,arguments)},oc=a._emscripten_bind_JoltInterface_Step_3=function(){return(oc=a._emscripten_bind_JoltInterface_Step_3=a.asm.Qa).apply(null,arguments)},pc=a._emscripten_bind_JoltInterface_GetPhysicsSystem_0=
function(){return(pc=a._emscripten_bind_JoltInterface_GetPhysicsSystem_0=a.asm.Ra).apply(null,arguments)},qc=a._emscripten_bind_JoltInterface___destroy___0=function(){return(qc=a._emscripten_bind_JoltInterface___destroy___0=a.asm.Sa).apply(null,arguments)},rc=a._emscripten_enum_Layers_MOVING=function(){return(rc=a._emscripten_enum_Layers_MOVING=a.asm.Ta).apply(null,arguments)},sc=a._emscripten_enum_Layers_NON_MOVING=function(){return(sc=a._emscripten_enum_Layers_NON_MOVING=a.asm.Ua).apply(null,arguments)},
tc=a._emscripten_enum_EMotionType_Static=function(){return(tc=a._emscripten_enum_EMotionType_Static=a.asm.Va).apply(null,arguments)},uc=a._emscripten_enum_EMotionType_Kinematic=function(){return(uc=a._emscripten_enum_EMotionType_Kinematic=a.asm.Wa).apply(null,arguments)},vc=a._emscripten_enum_EMotionType_Dynamic=function(){return(vc=a._emscripten_enum_EMotionType_Dynamic=a.asm.Xa).apply(null,arguments)},wc=a._emscripten_enum_EMotionQuality_Discrete=function(){return(wc=a._emscripten_enum_EMotionQuality_Discrete=
a.asm.Ya).apply(null,arguments)},xc=a._emscripten_enum_EMotionQuality_LinearCast=function(){return(xc=a._emscripten_enum_EMotionQuality_LinearCast=a.asm.Za).apply(null,arguments)},yc=a._emscripten_enum_EActivation_Activate=function(){return(yc=a._emscripten_enum_EActivation_Activate=a.asm._a).apply(null,arguments)},zc=a._emscripten_enum_EActivation_DontActivate=function(){return(zc=a._emscripten_enum_EActivation_DontActivate=a.asm.$a).apply(null,arguments)},Ma=a._malloc=function(){return(Ma=a._malloc=
a.asm.bb).apply(null,arguments)};a.___cxa_is_pointer_type=function(){return(a.___cxa_is_pointer_type=a.asm.cb).apply(null,arguments)};a.___start_em_js=42512;a.___stop_em_js=42610;var Ac;D=function Bc(){Ac||Cc();Ac||(D=Bc)};
function Cc(){function b(){if(!Ac&&(Ac=!0,a.calledRun=!0,!la)){ra=!0;ya(pa);aa(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();qa.unshift(c)}ya(qa)}}if(!(0<C)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)sa();ya(oa);0<C||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();Cc();function H(){}H.prototype=Object.create(H.prototype);H.prototype.constructor=H;H.prototype.eb=H;H.fb={};a.WrapperObject=H;function I(b){return(b||H).fb}a.getCache=I;function J(b,c){var e=I(c),g=e[b];if(g)return g;g=Object.create((c||H).prototype);g.ab=b;return e[b]=g}a.wrapPointer=J;a.castObject=function(b,c){return J(b.ab,c)};a.NULL=J(0);
a.destroy=function(b){if(!b.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";b.__destroy__();delete I(b.eb)[b.ab]};a.compare=function(b,c){return b.ab===c.ab};a.getPointer=function(b){return b.ab};a.getClass=function(b){return b.eb};function K(){throw"cannot construct a Shape, no constructor in IDL";}K.prototype=Object.create(H.prototype);K.prototype.constructor=K;K.prototype.eb=K;K.fb={};a.Shape=K;K.prototype.__destroy__=function(){Oa(this.ab)};
function L(){throw"cannot construct a VoidPtr, no constructor in IDL";}L.prototype=Object.create(H.prototype);L.prototype.constructor=L;L.prototype.eb=L;L.fb={};a.VoidPtr=L;L.prototype.__destroy__=function(){Pa(this.ab)};function N(b,c,e){b&&"object"===typeof b&&(b=b.ab);c&&"object"===typeof c&&(c=c.ab);e&&"object"===typeof e&&(e=e.ab);this.ab=void 0===b?Qa():void 0===c?_emscripten_bind_Vec3_Vec3_1(b):void 0===e?_emscripten_bind_Vec3_Vec3_2(b,c):Ra(b,c,e);I(N)[this.ab]=this}N.prototype=Object.create(H.prototype);
N.prototype.constructor=N;N.prototype.eb=N;N.fb={};a.Vec3=N;N.prototype.Length=function(){return Sa(this.ab)};N.prototype.GetX=function(){return Ta(this.ab)};N.prototype.GetY=function(){return Ua(this.ab)};N.prototype.GetZ=function(){return Va(this.ab)};N.prototype.SetX=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Wa(c,b)};N.prototype.SetY=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Xa(c,b)};
N.prototype.SetZ=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Ya(c,b)};N.prototype.__destroy__=function(){Za(this.ab)};function O(b,c,e,g){b&&"object"===typeof b&&(b=b.ab);c&&"object"===typeof c&&(c=c.ab);e&&"object"===typeof e&&(e=e.ab);g&&"object"===typeof g&&(g=g.ab);this.ab=void 0===b?$a():void 0===c?_emscripten_bind_Quat_Quat_1(b):void 0===e?_emscripten_bind_Quat_Quat_2(b,c):void 0===g?_emscripten_bind_Quat_Quat_3(b,c,e):ab(b,c,e,g);I(O)[this.ab]=this}O.prototype=Object.create(H.prototype);
O.prototype.constructor=O;O.prototype.eb=O;O.fb={};a.Quat=O;O.prototype.Length=function(){return bb(this.ab)};O.prototype.GetX=function(){return cb(this.ab)};O.prototype.GetY=function(){return db(this.ab)};O.prototype.GetZ=function(){return eb(this.ab)};O.prototype.GetW=function(){return fb(this.ab)};O.prototype.__destroy__=function(){gb(this.ab)};function P(){throw"cannot construct a PhysicsMaterial, no constructor in IDL";}P.prototype=Object.create(H.prototype);P.prototype.constructor=P;
P.prototype.eb=P;P.fb={};a.PhysicsMaterial=P;P.prototype.__destroy__=function(){hb(this.ab)};function R(b,c){b&&"object"===typeof b&&(b=b.ab);c&&"object"===typeof c&&(c=c.ab);this.ab=ib(b,c);I(R)[this.ab]=this}R.prototype=Object.create(K.prototype);R.prototype.constructor=R;R.prototype.eb=R;R.fb={};a.SphereShape=R;R.prototype.__destroy__=function(){jb(this.ab)};
function S(b,c,e){b&&"object"===typeof b&&(b=b.ab);c&&"object"===typeof c&&(c=c.ab);e&&"object"===typeof e&&(e=e.ab);this.ab=kb(b,c,e);I(S)[this.ab]=this}S.prototype=Object.create(K.prototype);S.prototype.constructor=S;S.prototype.eb=S;S.fb={};a.BoxShape=S;S.prototype.__destroy__=function(){lb(this.ab)};function T(b,c,e,g){b&&"object"===typeof b&&(b=b.ab);c&&"object"===typeof c&&(c=c.ab);e&&"object"===typeof e&&(e=e.ab);g&&"object"===typeof g&&(g=g.ab);this.ab=mb(b,c,e,g);I(T)[this.ab]=this}
T.prototype=Object.create(K.prototype);T.prototype.constructor=T;T.prototype.eb=T;T.fb={};a.CylinderShape=T;T.prototype.__destroy__=function(){nb(this.ab)};function U(b){b&&"object"===typeof b&&(b=b.ab);this.ab=void 0===b?ob():pb(b);I(U)[this.ab]=this}U.prototype=Object.create(H.prototype);U.prototype.constructor=U;U.prototype.eb=U;U.fb={};a.BodyID=U;U.prototype.__destroy__=function(){qb(this.ab)};function Body(){throw"cannot construct a Body, no constructor in IDL";}Body.prototype=Object.create(H.prototype);
Body.prototype.constructor=Body;Body.prototype.eb=Body;Body.fb={};a.Body=Body;Body.prototype.GetID=function(){return J(rb(this.ab),U)};Body.prototype.GetPosition=function(){return J(sb(this.ab),N)};Body.prototype.GetRotation=function(){return J(tb(this.ab),O)};Body.prototype.__destroy__=function(){ub(this.ab)};function W(){throw"cannot construct a BodyInterface, no constructor in IDL";}W.prototype=Object.create(H.prototype);W.prototype.constructor=W;W.prototype.eb=W;W.fb={};a.BodyInterface=W;
W.prototype.CreateBody=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);return J(vb(c,b),Body)};W.prototype.AddBody=function(b,c){var e=this.ab;b&&"object"===typeof b&&(b=b.ab);c&&"object"===typeof c&&(c=c.ab);wb(e,b,c)};W.prototype.CreateAndAddBody=function(b,c){var e=this.ab;b&&"object"===typeof b&&(b=b.ab);c&&"object"===typeof c&&(c=c.ab);return J(xb(e,b,c),U)};
W.prototype.GetPositionAndRotation=function(b,c,e){var g=this.ab;b&&"object"===typeof b&&(b=b.ab);c&&"object"===typeof c&&(c=c.ab);e&&"object"===typeof e&&(e=e.ab);yb(g,b,c,e)};W.prototype.__destroy__=function(){zb(this.ab)};function X(){throw"cannot construct a PhysicsSystem, no constructor in IDL";}X.prototype=Object.create(H.prototype);X.prototype.constructor=X;X.prototype.eb=X;X.fb={};a.PhysicsSystem=X;X.prototype.GetBodyInterface=function(){return J(Ab(this.ab),W)};X.prototype.__destroy__=function(){Bb(this.ab)};
function Y(b,c,e,g,h){b&&"object"===typeof b&&(b=b.ab);c&&"object"===typeof c&&(c=c.ab);e&&"object"===typeof e&&(e=e.ab);g&&"object"===typeof g&&(g=g.ab);h&&"object"===typeof h&&(h=h.ab);this.ab=Cb(b,c,e,g,h);I(Y)[this.ab]=this}Y.prototype=Object.create(H.prototype);Y.prototype.constructor=Y;Y.prototype.eb=Y;Y.fb={};a.BodyCreationSettings=Y;Y.prototype.get_mPosition=Y.prototype.Eb=function(){return J(Db(this.ab),N)};
Y.prototype.set_mPosition=Y.prototype.Zb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Eb(c,b)};Object.defineProperty(Y.prototype,"mPosition",{get:Y.prototype.Eb,set:Y.prototype.Zb});Y.prototype.get_mRotation=Y.prototype.Gb=function(){return J(Fb(this.ab),O)};Y.prototype.set_mRotation=Y.prototype.ac=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Gb(c,b)};Object.defineProperty(Y.prototype,"mRotation",{get:Y.prototype.Gb,set:Y.prototype.ac});
Y.prototype.get_mLinearVelocity=Y.prototype.yb=function(){return J(Hb(this.ab),N)};Y.prototype.set_mLinearVelocity=Y.prototype.Tb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Ib(c,b)};Object.defineProperty(Y.prototype,"mLinearVelocity",{get:Y.prototype.yb,set:Y.prototype.Tb});Y.prototype.get_mAngularVelocity=Y.prototype.tb=function(){return J(Jb(this.ab),N)};Y.prototype.set_mAngularVelocity=Y.prototype.Ob=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Kb(c,b)};
Object.defineProperty(Y.prototype,"mAngularVelocity",{get:Y.prototype.tb,set:Y.prototype.Ob});Y.prototype.get_mUserData=Y.prototype.Hb=function(){return Lb(this.ab)};Y.prototype.set_mUserData=Y.prototype.bc=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Mb(c,b)};Object.defineProperty(Y.prototype,"mUserData",{get:Y.prototype.Hb,set:Y.prototype.bc});Y.prototype.get_mObjectLayer=Y.prototype.Db=function(){return Nb(this.ab)};
Y.prototype.set_mObjectLayer=Y.prototype.Yb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Ob(c,b)};Object.defineProperty(Y.prototype,"mObjectLayer",{get:Y.prototype.Db,set:Y.prototype.Yb});Y.prototype.get_mMotionType=Y.prototype.Cb=function(){return Pb(this.ab)};Y.prototype.set_mMotionType=Y.prototype.Xb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Qb(c,b)};Object.defineProperty(Y.prototype,"mMotionType",{get:Y.prototype.Cb,set:Y.prototype.Xb});
Y.prototype.get_mAllowDynamicOrKinematic=Y.prototype.qb=function(){return!!Rb(this.ab)};Y.prototype.set_mAllowDynamicOrKinematic=Y.prototype.Lb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Sb(c,b)};Object.defineProperty(Y.prototype,"mAllowDynamicOrKinematic",{get:Y.prototype.qb,set:Y.prototype.Lb});Y.prototype.get_mIsSensor=Y.prototype.wb=function(){return!!Tb(this.ab)};Y.prototype.set_mIsSensor=Y.prototype.Rb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Ub(c,b)};
Object.defineProperty(Y.prototype,"mIsSensor",{get:Y.prototype.wb,set:Y.prototype.Rb});Y.prototype.get_mMotionQuality=Y.prototype.Bb=function(){return Vb(this.ab)};Y.prototype.set_mMotionQuality=Y.prototype.Wb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Wb(c,b)};Object.defineProperty(Y.prototype,"mMotionQuality",{get:Y.prototype.Bb,set:Y.prototype.Wb});Y.prototype.get_mAllowSleeping=Y.prototype.rb=function(){return!!Xb(this.ab)};
Y.prototype.set_mAllowSleeping=Y.prototype.Mb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);Yb(c,b)};Object.defineProperty(Y.prototype,"mAllowSleeping",{get:Y.prototype.rb,set:Y.prototype.Mb});Y.prototype.get_mFriction=Y.prototype.ub=function(){return Zb(this.ab)};Y.prototype.set_mFriction=Y.prototype.Pb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);$b(c,b)};Object.defineProperty(Y.prototype,"mFriction",{get:Y.prototype.ub,set:Y.prototype.Pb});
Y.prototype.get_mRestitution=Y.prototype.Fb=function(){return ac(this.ab)};Y.prototype.set_mRestitution=Y.prototype.$b=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);bc(c,b)};Object.defineProperty(Y.prototype,"mRestitution",{get:Y.prototype.Fb,set:Y.prototype.$b});Y.prototype.get_mLinearDamping=Y.prototype.xb=function(){return cc(this.ab)};Y.prototype.set_mLinearDamping=Y.prototype.Sb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);dc(c,b)};
Object.defineProperty(Y.prototype,"mLinearDamping",{get:Y.prototype.xb,set:Y.prototype.Sb});Y.prototype.get_mAngularDamping=Y.prototype.sb=function(){return ec(this.ab)};Y.prototype.set_mAngularDamping=Y.prototype.Nb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);fc(c,b)};Object.defineProperty(Y.prototype,"mAngularDamping",{get:Y.prototype.sb,set:Y.prototype.Nb});Y.prototype.get_mMaxLinearVelocity=Y.prototype.Ab=function(){return gc(this.ab)};
Y.prototype.set_mMaxLinearVelocity=Y.prototype.Vb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);hc(c,b)};Object.defineProperty(Y.prototype,"mMaxLinearVelocity",{get:Y.prototype.Ab,set:Y.prototype.Vb});Y.prototype.get_mMaxAngularVelocity=Y.prototype.zb=function(){return ic(this.ab)};Y.prototype.set_mMaxAngularVelocity=Y.prototype.Ub=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);jc(c,b)};Object.defineProperty(Y.prototype,"mMaxAngularVelocity",{get:Y.prototype.zb,set:Y.prototype.Ub});
Y.prototype.get_mGravityFactor=Y.prototype.vb=function(){return kc(this.ab)};Y.prototype.set_mGravityFactor=Y.prototype.Qb=function(b){var c=this.ab;b&&"object"===typeof b&&(b=b.ab);lc(c,b)};Object.defineProperty(Y.prototype,"mGravityFactor",{get:Y.prototype.vb,set:Y.prototype.Qb});Y.prototype.__destroy__=function(){mc(this.ab)};function Z(){this.ab=nc();I(Z)[this.ab]=this}Z.prototype=Object.create(H.prototype);Z.prototype.constructor=Z;Z.prototype.eb=Z;Z.fb={};a.JoltInterface=Z;
Z.prototype.Step=function(b,c,e){var g=this.ab;b&&"object"===typeof b&&(b=b.ab);c&&"object"===typeof c&&(c=c.ab);e&&"object"===typeof e&&(e=e.ab);oc(g,b,c,e)};Z.prototype.GetPhysicsSystem=function(){return J(pc(this.ab),X)};Z.prototype.__destroy__=function(){qc(this.ab)};(function(){function b(){a.MOVING=rc();a.NON_MOVING=sc();a.Static=tc();a.Kinematic=uc();a.Dynamic=vc();a.Discrete=wc();a.LinearCast=xc();a.Activate=yc();a.DontActivate=zc()}ra?b():pa.unshift(b)})();this.Jolt=a;


  return Jolt.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Jolt;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Jolt; });
else if (typeof exports === 'object')
  exports["Jolt"] = Jolt;
