// This is JoltPhysics.js, a web assembly version of JoltPhysics

var Jolt = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Jolt) {
  Jolt = Jolt || {};


var a;a||(a=typeof Jolt !== 'undefined' ? Jolt : {});var aa,ba;a.ready=new Promise(function(b,c){aa=b;ba=c});var ca=Object.assign({},a),da="./this.program",ea="object"==typeof window,m="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,n="",ha,q,r,fs,u,ia;
if(fa)n=m?require("path").dirname(n)+"/":__dirname+"/",ia=()=>{u||(fs=require("fs"),u=require("path"))},ha=function(b,c){ia();b=u.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")},r=b=>{b=ha(b,!0);b.buffer||(b=new Uint8Array(b));return b},q=(b,c,e)=>{ia();b=u.normalize(b);fs.readFile(b,function(f,g){f?e(f):c(g.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",function(b){throw b;
}),a.inspect=function(){return"[Emscripten Module object]"};else if(ea||m)m?n=self.location.href:"undefined"!=typeof document&&document.currentScript&&(n=document.currentScript.src),_scriptDir&&(n=_scriptDir),0!==n.indexOf("blob:")?n=n.substr(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1):n="",ha=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},m&&(r=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),
q=(b,c,e)=>{var f=new XMLHttpRequest;f.open("GET",b,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):e()};f.onerror=e;f.send(null)};var ja=a.print||console.log.bind(console),v=a.printErr||console.warn.bind(console);Object.assign(a,ca);ca=null;a.thisProgram&&(da=a.thisProgram);var w;a.wasmBinary&&(w=a.wasmBinary);var noExitRuntime=a.noExitRuntime||!0;"object"!=typeof WebAssembly&&x("no native wasm support detected");
var ka,la=!1,ma="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(b,c){for(var e=c+NaN,f=c;b[f]&&!(f>=e);)++f;if(16<f-c&&b.buffer&&ma)return ma.decode(b.subarray(c,f));for(e="";c<f;){var g=b[c++];if(g&128){var h=b[c++]&63;if(192==(g&224))e+=String.fromCharCode((g&31)<<6|h);else{var D=b[c++]&63;g=224==(g&240)?(g&15)<<12|h<<6|D:(g&7)<<18|h<<12|D<<6|b[c++]&63;65536>g?e+=String.fromCharCode(g):(g-=65536,e+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else e+=String.fromCharCode(g)}return e}var y,z,A,B,oa=[],pa=[],qa=[],ra=!1;
function sa(){var b=a.preRun.shift();oa.unshift(b)}var C=0,ta=null,E=null;function x(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";v(b);la=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ba(b);throw b;}function ua(){return F.startsWith("data:application/octet-stream;base64,")}var F;F="jolt.wasm.wasm";if(!ua()){var va=F;F=a.locateFile?a.locateFile(va,n):n+va}
function wa(){var b=F;try{if(b==F&&w)return new Uint8Array(w);if(r)return r(b);throw"both async and sync fetching of the wasm failed";}catch(c){x(c)}}
function xa(){if(!w&&(ea||m)){if("function"==typeof fetch&&!F.startsWith("file://"))return fetch(F,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+F+"'";return b.arrayBuffer()}).catch(function(){return wa()});if(q)return new Promise(function(b,c){q(F,function(e){b(new Uint8Array(e))},c)})}return Promise.resolve().then(function(){return wa()})}function ya(b){for(;0<b.length;)b.shift()(a)}
function za(b){this.la=b-24;this.Ca=function(c){B[this.la+4>>2]=c};this.za=function(c){B[this.la+8>>2]=c};this.Aa=function(){A[this.la>>2]=0};this.ya=function(){y[this.la+12>>0]=0};this.Ba=function(){y[this.la+13>>0]=0};this.wa=function(c,e){this.xa();this.Ca(c);this.za(e);this.Aa();this.ya();this.Ba()};this.xa=function(){B[this.la+16>>2]=0}}var Aa=0,Ba={};
function Fa(){if(!Ga){var b={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},c;for(c in Ba)void 0===Ba[c]?delete b[c]:b[c]=Ba[c];var e=[];for(c in b)e.push(c+"="+b[c]);Ga=e}return Ga}var Ga,Ha=[null,[],[]];function G(b){return 0===b%4&&(0!==b%100||0===b%400)}
var Ia=[31,29,31,30,31,30,31,31,30,31,30,31],Ja=[31,28,31,30,31,30,31,31,30,31,30,31];
function Ka(b){for(var c=0,e=0;e<b.length;++e){var f=b.charCodeAt(e);127>=f?c++:2047>=f?c+=2:55296<=f&&57343>=f?(c+=4,++e):c+=3}c=Array(c+1);f=c.length;e=0;if(0<f){f=e+f-1;for(var g=0;g<b.length;++g){var h=b.charCodeAt(g);if(55296<=h&&57343>=h){var D=b.charCodeAt(++g);h=65536+((h&1023)<<10)|D&1023}if(127>=h){if(e>=f)break;c[e++]=h}else{if(2047>=h){if(e+1>=f)break;c[e++]=192|h>>6}else{if(65535>=h){if(e+2>=f)break;c[e++]=224|h>>12}else{if(e+3>=f)break;c[e++]=240|h>>18;c[e++]=128|h>>12&63}c[e++]=128|
h>>6&63}c[e++]=128|h&63}}c[e]=0}return c}
function La(b,c,e,f){function g(d,k,l){for(d="number"==typeof d?d.toString():d||"";d.length<k;)d=l[0]+d;return d}function h(d,k){return g(d,k,"0")}function D(d,k){function l(Ca){return 0>Ca?-1:0<Ca?1:0}var L;0===(L=l(d.getFullYear()-k.getFullYear()))&&0===(L=l(d.getMonth()-k.getMonth()))&&(L=l(d.getDate()-k.getDate()));return L}function V(d){switch(d.getDay()){case 0:return new Date(d.getFullYear()-1,11,29);case 1:return d;case 2:return new Date(d.getFullYear(),0,3);case 3:return new Date(d.getFullYear(),
0,2);case 4:return new Date(d.getFullYear(),0,1);case 5:return new Date(d.getFullYear()-1,11,31);case 6:return new Date(d.getFullYear()-1,11,30)}}function P(d){var k=d.ra;for(d=new Date((new Date(d.sa+1900,0,1)).getTime());0<k;){var l=d.getMonth(),L=(G(d.getFullYear())?Ia:Ja)[l];if(k>L-d.getDate())k-=L-d.getDate()+1,d.setDate(1),11>l?d.setMonth(l+1):(d.setMonth(0),d.setFullYear(d.getFullYear()+1));else{d.setDate(d.getDate()+k);break}}l=new Date(d.getFullYear()+1,0,4);k=V(new Date(d.getFullYear(),
0,4));l=V(l);return 0>=D(k,d)?0>=D(l,d)?d.getFullYear()+1:d.getFullYear():d.getFullYear()-1}var t=A[f+40>>2];f={Fa:A[f>>2],Ea:A[f+4>>2],ta:A[f+8>>2],va:A[f+12>>2],ua:A[f+16>>2],sa:A[f+20>>2],qa:A[f+24>>2],ra:A[f+28>>2],Ha:A[f+32>>2],Da:A[f+36>>2],Ga:t?t?na(z,t):"":""};e=e?na(z,e):"";t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in t)e=e.replace(new RegExp(p,"g"),t[p]);var Da="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Ea="January February March April May June July August September October November December".split(" ");t={"%a":function(d){return Da[d.qa].substring(0,3)},"%A":function(d){return Da[d.qa]},"%b":function(d){return Ea[d.ua].substring(0,
3)},"%B":function(d){return Ea[d.ua]},"%C":function(d){return h((d.sa+1900)/100|0,2)},"%d":function(d){return h(d.va,2)},"%e":function(d){return g(d.va,2," ")},"%g":function(d){return P(d).toString().substring(2)},"%G":function(d){return P(d)},"%H":function(d){return h(d.ta,2)},"%I":function(d){d=d.ta;0==d?d=12:12<d&&(d-=12);return h(d,2)},"%j":function(d){for(var k=0,l=0;l<=d.ua-1;k+=(G(d.sa+1900)?Ia:Ja)[l++]);return h(d.va+k,3)},"%m":function(d){return h(d.ua+1,2)},"%M":function(d){return h(d.Ea,
2)},"%n":function(){return"\n"},"%p":function(d){return 0<=d.ta&&12>d.ta?"AM":"PM"},"%S":function(d){return h(d.Fa,2)},"%t":function(){return"\t"},"%u":function(d){return d.qa||7},"%U":function(d){return h(Math.floor((d.ra+7-d.qa)/7),2)},"%V":function(d){var k=Math.floor((d.ra+7-(d.qa+6)%7)/7);2>=(d.qa+371-d.ra-2)%7&&k++;if(k)53==k&&(l=(d.qa+371-d.ra)%7,4==l||3==l&&G(d.sa)||(k=1));else{k=52;var l=(d.qa+7-d.ra-1)%7;(4==l||5==l&&G(d.sa%400-1))&&k++}return h(k,2)},"%w":function(d){return d.qa},"%W":function(d){return h(Math.floor((d.ra+
7-(d.qa+6)%7)/7),2)},"%y":function(d){return(d.sa+1900).toString().substring(2)},"%Y":function(d){return d.sa+1900},"%z":function(d){d=d.Da;var k=0<=d;d=Math.abs(d)/60;return(k?"+":"-")+String("0000"+(d/60*100+d%60)).slice(-4)},"%Z":function(d){return d.Ga},"%%":function(){return"%"}};e=e.replace(/%%/g,"\x00\x00");for(p in t)e.includes(p)&&(e=e.replace(new RegExp(p,"g"),t[p](f)));e=e.replace(/\0\0/g,"%");p=Ka(e);if(p.length>c)return 0;y.set(p,b);return p.length-1}
var Na={b:function(b){return Ma(b+24)+24},a:function(b,c,e){(new za(b)).wa(c,e);Aa++;throw b;},d:function(){x("")},l:function(){return z.length},e:fa?()=>{var b=process.hrtime();return 1E3*b[0]+b[1]/1E6}:()=>performance.now(),j:function(b,c,e){z.copyWithin(b,c,c+e)},i:function(){x("OOM")},n:function(b,c){var e=0;Fa().forEach(function(f,g){var h=c+e;g=B[b+4*g>>2]=h;for(h=0;h<f.length;++h)y[g++>>0]=f.charCodeAt(h);y[g>>0]=0;e+=f.length+1});return 0},f:function(b,c){var e=Fa();B[b>>2]=e.length;var f=
0;e.forEach(function(g){f+=g.length+1});B[c>>2]=f;return 0},g:function(){return 52},h:function(){return 52},k:function(){return 70},c:function(b,c,e,f){for(var g=0,h=0;h<e;h++){var D=B[c>>2],V=B[c+4>>2];c+=8;for(var P=0;P<V;P++){var t=z[D+P],p=Ha[b];0===t||10===t?((1===b?ja:v)(na(p,0)),p.length=0):p.push(t)}g+=V}B[f>>2]=g;return 0},m:function(b,c,e,f){return La(b,c,e,f)}};
(function(){function b(g){a.asm=g.exports;ka=a.asm.o;g=ka.buffer;a.HEAP8=y=new Int8Array(g);a.HEAP16=new Int16Array(g);a.HEAP32=A=new Int32Array(g);a.HEAPU8=z=new Uint8Array(g);a.HEAPU16=new Uint16Array(g);a.HEAPU32=B=new Uint32Array(g);a.HEAPF32=new Float32Array(g);a.HEAPF64=new Float64Array(g);pa.unshift(a.asm.p);C--;a.monitorRunDependencies&&a.monitorRunDependencies(C);0==C&&(null!==ta&&(clearInterval(ta),ta=null),E&&(g=E,E=null,g()))}function c(g){b(g.instance)}function e(g){return xa().then(function(h){return WebAssembly.instantiate(h,
f)}).then(function(h){return h}).then(g,function(h){v("failed to asynchronously prepare wasm: "+h);x(h)})}var f={a:Na};C++;a.monitorRunDependencies&&a.monitorRunDependencies(C);if(a.instantiateWasm)try{return a.instantiateWasm(f,b)}catch(g){return v("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return w||"function"!=typeof WebAssembly.instantiateStreaming||ua()||F.startsWith("file://")||fa||"function"!=typeof fetch?e(c):fetch(F,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,
f).then(c,function(h){v("wasm streaming compile failed: "+h);v("falling back to ArrayBuffer instantiation");return e(c)})})})().catch(ba);return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.p).apply(null,arguments)};
var Oa=a._emscripten_bind_Shape___destroy___0=function(){return(Oa=a._emscripten_bind_Shape___destroy___0=a.asm.q).apply(null,arguments)},Pa=a._emscripten_bind_VoidPtr___destroy___0=function(){return(Pa=a._emscripten_bind_VoidPtr___destroy___0=a.asm.r).apply(null,arguments)},Qa=a._emscripten_bind_Vec3_Vec3_0=function(){return(Qa=a._emscripten_bind_Vec3_Vec3_0=a.asm.s).apply(null,arguments)},Ra=a._emscripten_bind_Vec3_Vec3_3=function(){return(Ra=a._emscripten_bind_Vec3_Vec3_3=a.asm.t).apply(null,arguments)},
Sa=a._emscripten_bind_Vec3_Length_0=function(){return(Sa=a._emscripten_bind_Vec3_Length_0=a.asm.u).apply(null,arguments)},Ta=a._emscripten_bind_Vec3_GetX_0=function(){return(Ta=a._emscripten_bind_Vec3_GetX_0=a.asm.v).apply(null,arguments)},Ua=a._emscripten_bind_Vec3_GetY_0=function(){return(Ua=a._emscripten_bind_Vec3_GetY_0=a.asm.w).apply(null,arguments)},Va=a._emscripten_bind_Vec3_GetZ_0=function(){return(Va=a._emscripten_bind_Vec3_GetZ_0=a.asm.x).apply(null,arguments)},Wa=a._emscripten_bind_Vec3_SetX_1=
function(){return(Wa=a._emscripten_bind_Vec3_SetX_1=a.asm.y).apply(null,arguments)},Xa=a._emscripten_bind_Vec3_SetY_1=function(){return(Xa=a._emscripten_bind_Vec3_SetY_1=a.asm.z).apply(null,arguments)},Ya=a._emscripten_bind_Vec3_SetZ_1=function(){return(Ya=a._emscripten_bind_Vec3_SetZ_1=a.asm.A).apply(null,arguments)},Za=a._emscripten_bind_Vec3___destroy___0=function(){return(Za=a._emscripten_bind_Vec3___destroy___0=a.asm.B).apply(null,arguments)},$a=a._emscripten_bind_Quat_Quat_0=function(){return($a=
a._emscripten_bind_Quat_Quat_0=a.asm.C).apply(null,arguments)},ab=a._emscripten_bind_Quat_Quat_4=function(){return(ab=a._emscripten_bind_Quat_Quat_4=a.asm.D).apply(null,arguments)},bb=a._emscripten_bind_Quat_Length_0=function(){return(bb=a._emscripten_bind_Quat_Length_0=a.asm.E).apply(null,arguments)},cb=a._emscripten_bind_Quat_GetX_0=function(){return(cb=a._emscripten_bind_Quat_GetX_0=a.asm.F).apply(null,arguments)},db=a._emscripten_bind_Quat_GetY_0=function(){return(db=a._emscripten_bind_Quat_GetY_0=
a.asm.G).apply(null,arguments)},eb=a._emscripten_bind_Quat_GetZ_0=function(){return(eb=a._emscripten_bind_Quat_GetZ_0=a.asm.H).apply(null,arguments)},fb=a._emscripten_bind_Quat_GetW_0=function(){return(fb=a._emscripten_bind_Quat_GetW_0=a.asm.I).apply(null,arguments)},gb=a._emscripten_bind_Quat___destroy___0=function(){return(gb=a._emscripten_bind_Quat___destroy___0=a.asm.J).apply(null,arguments)},hb=a._emscripten_bind_PhysicsMaterial___destroy___0=function(){return(hb=a._emscripten_bind_PhysicsMaterial___destroy___0=
a.asm.K).apply(null,arguments)},ib=a._emscripten_bind_SphereShape_SphereShape_2=function(){return(ib=a._emscripten_bind_SphereShape_SphereShape_2=a.asm.L).apply(null,arguments)},jb=a._emscripten_bind_SphereShape___destroy___0=function(){return(jb=a._emscripten_bind_SphereShape___destroy___0=a.asm.M).apply(null,arguments)},kb=a._emscripten_bind_BoxShape_BoxShape_3=function(){return(kb=a._emscripten_bind_BoxShape_BoxShape_3=a.asm.N).apply(null,arguments)},lb=a._emscripten_bind_BoxShape___destroy___0=
function(){return(lb=a._emscripten_bind_BoxShape___destroy___0=a.asm.O).apply(null,arguments)},mb=a._emscripten_bind_CylinderShape_CylinderShape_4=function(){return(mb=a._emscripten_bind_CylinderShape_CylinderShape_4=a.asm.P).apply(null,arguments)},nb=a._emscripten_bind_CylinderShape___destroy___0=function(){return(nb=a._emscripten_bind_CylinderShape___destroy___0=a.asm.Q).apply(null,arguments)},ob=a._emscripten_bind_BodyID_BodyID_0=function(){return(ob=a._emscripten_bind_BodyID_BodyID_0=a.asm.R).apply(null,
arguments)},pb=a._emscripten_bind_BodyID_BodyID_1=function(){return(pb=a._emscripten_bind_BodyID_BodyID_1=a.asm.S).apply(null,arguments)},qb=a._emscripten_bind_BodyID_GetIndexAndSequenceNumber_0=function(){return(qb=a._emscripten_bind_BodyID_GetIndexAndSequenceNumber_0=a.asm.T).apply(null,arguments)},rb=a._emscripten_bind_BodyID___destroy___0=function(){return(rb=a._emscripten_bind_BodyID___destroy___0=a.asm.U).apply(null,arguments)},sb=a._emscripten_bind_BodyInterface_CreateAndAddBody_2=function(){return(sb=
a._emscripten_bind_BodyInterface_CreateAndAddBody_2=a.asm.V).apply(null,arguments)},tb=a._emscripten_bind_BodyInterface_GetPositionAndRotation_3=function(){return(tb=a._emscripten_bind_BodyInterface_GetPositionAndRotation_3=a.asm.W).apply(null,arguments)},ub=a._emscripten_bind_BodyInterface___destroy___0=function(){return(ub=a._emscripten_bind_BodyInterface___destroy___0=a.asm.X).apply(null,arguments)},vb=a._emscripten_bind_PhysicsSystem_GetBodyInterface_0=function(){return(vb=a._emscripten_bind_PhysicsSystem_GetBodyInterface_0=
a.asm.Y).apply(null,arguments)},wb=a._emscripten_bind_PhysicsSystem___destroy___0=function(){return(wb=a._emscripten_bind_PhysicsSystem___destroy___0=a.asm.Z).apply(null,arguments)},xb=a._emscripten_bind_BodyCreationSettings_BodyCreationSettings_5=function(){return(xb=a._emscripten_bind_BodyCreationSettings_BodyCreationSettings_5=a.asm._).apply(null,arguments)},yb=a._emscripten_bind_BodyCreationSettings___destroy___0=function(){return(yb=a._emscripten_bind_BodyCreationSettings___destroy___0=a.asm.$).apply(null,
arguments)},zb=a._emscripten_bind_JoltInterface_JoltInterface_0=function(){return(zb=a._emscripten_bind_JoltInterface_JoltInterface_0=a.asm.aa).apply(null,arguments)},Ab=a._emscripten_bind_JoltInterface_Step_3=function(){return(Ab=a._emscripten_bind_JoltInterface_Step_3=a.asm.ba).apply(null,arguments)},Bb=a._emscripten_bind_JoltInterface_GetPhysicsSystem_0=function(){return(Bb=a._emscripten_bind_JoltInterface_GetPhysicsSystem_0=a.asm.ca).apply(null,arguments)},Cb=a._emscripten_bind_JoltInterface___destroy___0=
function(){return(Cb=a._emscripten_bind_JoltInterface___destroy___0=a.asm.da).apply(null,arguments)},Db=a._emscripten_enum_Layers_MOVING=function(){return(Db=a._emscripten_enum_Layers_MOVING=a.asm.ea).apply(null,arguments)},Eb=a._emscripten_enum_Layers_NON_MOVING=function(){return(Eb=a._emscripten_enum_Layers_NON_MOVING=a.asm.fa).apply(null,arguments)},Fb=a._emscripten_enum_EMotionType_Static=function(){return(Fb=a._emscripten_enum_EMotionType_Static=a.asm.ga).apply(null,arguments)},Gb=a._emscripten_enum_EMotionType_Kinematic=
function(){return(Gb=a._emscripten_enum_EMotionType_Kinematic=a.asm.ha).apply(null,arguments)},Hb=a._emscripten_enum_EMotionType_Dynamic=function(){return(Hb=a._emscripten_enum_EMotionType_Dynamic=a.asm.ia).apply(null,arguments)},Ib=a._emscripten_enum_EActivation_Activate=function(){return(Ib=a._emscripten_enum_EActivation_Activate=a.asm.ja).apply(null,arguments)},Jb=a._emscripten_enum_EActivation_DontActivate=function(){return(Jb=a._emscripten_enum_EActivation_DontActivate=a.asm.ka).apply(null,arguments)},
Ma=a._malloc=function(){return(Ma=a._malloc=a.asm.ma).apply(null,arguments)};a.___cxa_is_pointer_type=function(){return(a.___cxa_is_pointer_type=a.asm.na).apply(null,arguments)};a.___start_em_js=42512;a.___stop_em_js=42610;var Kb;E=function Lb(){Kb||Mb();Kb||(E=Lb)};
function Mb(){function b(){if(!Kb&&(Kb=!0,a.calledRun=!0,!la)){ra=!0;ya(pa);aa(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();qa.unshift(c)}ya(qa)}}if(!(0<C)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)sa();ya(oa);0<C||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();Mb();function H(){}H.prototype=Object.create(H.prototype);H.prototype.constructor=H;H.prototype.oa=H;H.pa={};a.WrapperObject=H;function I(b){return(b||H).pa}a.getCache=I;function J(b,c){var e=I(c),f=e[b];if(f)return f;f=Object.create((c||H).prototype);f.la=b;return e[b]=f}a.wrapPointer=J;a.castObject=function(b,c){return J(b.la,c)};a.NULL=J(0);
a.destroy=function(b){if(!b.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";b.__destroy__();delete I(b.oa)[b.la]};a.compare=function(b,c){return b.la===c.la};a.getPointer=function(b){return b.la};a.getClass=function(b){return b.oa};function K(){throw"cannot construct a Shape, no constructor in IDL";}K.prototype=Object.create(H.prototype);K.prototype.constructor=K;K.prototype.oa=K;K.pa={};a.Shape=K;K.prototype.__destroy__=function(){Oa(this.la)};
function M(){throw"cannot construct a VoidPtr, no constructor in IDL";}M.prototype=Object.create(H.prototype);M.prototype.constructor=M;M.prototype.oa=M;M.pa={};a.VoidPtr=M;M.prototype.__destroy__=function(){Pa(this.la)};function N(b,c,e){b&&"object"===typeof b&&(b=b.la);c&&"object"===typeof c&&(c=c.la);e&&"object"===typeof e&&(e=e.la);this.la=void 0===b?Qa():void 0===c?_emscripten_bind_Vec3_Vec3_1(b):void 0===e?_emscripten_bind_Vec3_Vec3_2(b,c):Ra(b,c,e);I(N)[this.la]=this}N.prototype=Object.create(H.prototype);
N.prototype.constructor=N;N.prototype.oa=N;N.pa={};a.Vec3=N;N.prototype.Length=function(){return Sa(this.la)};N.prototype.GetX=function(){return Ta(this.la)};N.prototype.GetY=function(){return Ua(this.la)};N.prototype.GetZ=function(){return Va(this.la)};N.prototype.SetX=function(b){var c=this.la;b&&"object"===typeof b&&(b=b.la);Wa(c,b)};N.prototype.SetY=function(b){var c=this.la;b&&"object"===typeof b&&(b=b.la);Xa(c,b)};
N.prototype.SetZ=function(b){var c=this.la;b&&"object"===typeof b&&(b=b.la);Ya(c,b)};N.prototype.__destroy__=function(){Za(this.la)};function O(b,c,e,f){b&&"object"===typeof b&&(b=b.la);c&&"object"===typeof c&&(c=c.la);e&&"object"===typeof e&&(e=e.la);f&&"object"===typeof f&&(f=f.la);this.la=void 0===b?$a():void 0===c?_emscripten_bind_Quat_Quat_1(b):void 0===e?_emscripten_bind_Quat_Quat_2(b,c):void 0===f?_emscripten_bind_Quat_Quat_3(b,c,e):ab(b,c,e,f);I(O)[this.la]=this}O.prototype=Object.create(H.prototype);
O.prototype.constructor=O;O.prototype.oa=O;O.pa={};a.Quat=O;O.prototype.Length=function(){return bb(this.la)};O.prototype.GetX=function(){return cb(this.la)};O.prototype.GetY=function(){return db(this.la)};O.prototype.GetZ=function(){return eb(this.la)};O.prototype.GetW=function(){return fb(this.la)};O.prototype.__destroy__=function(){gb(this.la)};function Q(){throw"cannot construct a PhysicsMaterial, no constructor in IDL";}Q.prototype=Object.create(H.prototype);Q.prototype.constructor=Q;
Q.prototype.oa=Q;Q.pa={};a.PhysicsMaterial=Q;Q.prototype.__destroy__=function(){hb(this.la)};function R(b,c){b&&"object"===typeof b&&(b=b.la);c&&"object"===typeof c&&(c=c.la);this.la=ib(b,c);I(R)[this.la]=this}R.prototype=Object.create(K.prototype);R.prototype.constructor=R;R.prototype.oa=R;R.pa={};a.SphereShape=R;R.prototype.__destroy__=function(){jb(this.la)};
function S(b,c,e){b&&"object"===typeof b&&(b=b.la);c&&"object"===typeof c&&(c=c.la);e&&"object"===typeof e&&(e=e.la);this.la=kb(b,c,e);I(S)[this.la]=this}S.prototype=Object.create(K.prototype);S.prototype.constructor=S;S.prototype.oa=S;S.pa={};a.BoxShape=S;S.prototype.__destroy__=function(){lb(this.la)};function T(b,c,e,f){b&&"object"===typeof b&&(b=b.la);c&&"object"===typeof c&&(c=c.la);e&&"object"===typeof e&&(e=e.la);f&&"object"===typeof f&&(f=f.la);this.la=mb(b,c,e,f);I(T)[this.la]=this}
T.prototype=Object.create(K.prototype);T.prototype.constructor=T;T.prototype.oa=T;T.pa={};a.CylinderShape=T;T.prototype.__destroy__=function(){nb(this.la)};function U(b){b&&"object"===typeof b&&(b=b.la);this.la=void 0===b?ob():pb(b);I(U)[this.la]=this}U.prototype=Object.create(H.prototype);U.prototype.constructor=U;U.prototype.oa=U;U.pa={};a.BodyID=U;U.prototype.GetIndexAndSequenceNumber=function(){return qb(this.la)};U.prototype.__destroy__=function(){rb(this.la)};
function W(){throw"cannot construct a BodyInterface, no constructor in IDL";}W.prototype=Object.create(H.prototype);W.prototype.constructor=W;W.prototype.oa=W;W.pa={};a.BodyInterface=W;W.prototype.CreateAndAddBody=function(b,c){var e=this.la;b&&"object"===typeof b&&(b=b.la);c&&"object"===typeof c&&(c=c.la);return J(sb(e,b,c),U)};
W.prototype.GetPositionAndRotation=function(b,c,e){var f=this.la;b&&"object"===typeof b&&(b=b.la);c&&"object"===typeof c&&(c=c.la);e&&"object"===typeof e&&(e=e.la);tb(f,b,c,e)};W.prototype.__destroy__=function(){ub(this.la)};function X(){throw"cannot construct a PhysicsSystem, no constructor in IDL";}X.prototype=Object.create(H.prototype);X.prototype.constructor=X;X.prototype.oa=X;X.pa={};a.PhysicsSystem=X;X.prototype.GetBodyInterface=function(){return J(vb(this.la),W)};X.prototype.__destroy__=function(){wb(this.la)};
function Y(b,c,e,f,g){b&&"object"===typeof b&&(b=b.la);c&&"object"===typeof c&&(c=c.la);e&&"object"===typeof e&&(e=e.la);f&&"object"===typeof f&&(f=f.la);g&&"object"===typeof g&&(g=g.la);this.la=xb(b,c,e,f,g);I(Y)[this.la]=this}Y.prototype=Object.create(H.prototype);Y.prototype.constructor=Y;Y.prototype.oa=Y;Y.pa={};a.BodyCreationSettings=Y;Y.prototype.__destroy__=function(){yb(this.la)};function Z(){this.la=zb();I(Z)[this.la]=this}Z.prototype=Object.create(H.prototype);Z.prototype.constructor=Z;
Z.prototype.oa=Z;Z.pa={};a.JoltInterface=Z;Z.prototype.Step=function(b,c,e){var f=this.la;b&&"object"===typeof b&&(b=b.la);c&&"object"===typeof c&&(c=c.la);e&&"object"===typeof e&&(e=e.la);Ab(f,b,c,e)};Z.prototype.GetPhysicsSystem=function(){return J(Bb(this.la),X)};Z.prototype.__destroy__=function(){Cb(this.la)};(function(){function b(){a.MOVING=Db();a.NON_MOVING=Eb();a.Static=Fb();a.Kinematic=Gb();a.Dynamic=Hb();a.Activate=Ib();a.DontActivate=Jb()}ra?b():pa.unshift(b)})();this.Jolt=a;


  return Jolt.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Jolt;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Jolt; });
else if (typeof exports === 'object')
  exports["Jolt"] = Jolt;
