name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  id-token: write # Required for OIDC
  contents: write # Required to publish the examples
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        registry-url: 'https://registry.npmjs.org'

    - name: Build
      run: ./ci/build-examples.sh
      shell: bash

    - name: Deploy Examples
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Examples
        force_orphan: true

    - name: Publish NPM
      run: ./ci/npm-publish.sh
